### PR TITLE
Email validation for username

### PR DESCRIPTION
**Pull request by ghost**
Fix Issue #1042 

Keep old validation as a secondary for usernames that are not necessarily email addresses.

### CODE REVIEW

**Comment by Skywalker-11** [comment]
Have you tested if there could be problems with the sql queries?
The change also breaks global admins without mail account.

**Comment by ghost** [comment]
"The change also breaks global admins without mail account."

@Skywalker-11 I Where are you seeing this?  I have the code in place on my system and have a global admin that is not a mail account.  The code validates using both methods.

**Comment by ghost** [comment]
Hold on merging this, though.  I did find an issue with the sanitization that also needs addressed.  This alone is not enough to resolve the specific apostrophie issue.  I'll continue with it as soon as I arrive at work.  I'll take a closer look at the sql queries as well that interact with the username.

**Comment by Skywalker-11** [comment]
@shawniverson sorry I overlooked the else statement. So no explicit problem with global admins.

We should also check the perl code (Black list + spam settings) as it could also circumvent the filters depending on how it is escaped in mysql and perl

**Comment by ghost** [comment]
@Skywalker-11 Good idea.

**Comment by ghost** [comment]
Tests done:

- Password reset
- Alternate recipient email addresses honor "'" in address in user management and email release
- Report searching using username/email containing "'"
- MailScanner proper interpretation of escaped "'" in black and whitelists via SQLBlackWhiteList.pm
- MailScanner proper interpretation of escaped "'" of user in SQLSpamSettings.pm
- Successful login with user containing "'"
- Storage of username as an safe (escaped) value containing "'"
- Display of unescaped username to screen
- Edit/Delete/Logout user with "'"
- Change password as user with "'"
- Removal of escapes in audit log report display
- details.php add to whitelist/blacklist email with "'"
- Filters storing and using "'" correctly (bug found and squashed)
- Saved filters properly save and load "'" in value field
- Duplicate user check properly handles "'"
- Domain admin functionality still working with presence of "'" in usernames self & targets
- Quarantine reports handle email addresses with "'" in username
- Turn magic_quotes_gpc on and retain functionality

**Comment by ghost** [comment]
You'll notice the odd construct `safe_value(stripslashes($var))` throughout the code.  This is precautionary and has a normalizing effect on the escaping of single quotes.  Under normal conditions, it will remove the slashes and add them back.  However, it will also guard against a situation in which a $var was not properly escaped elsewhere in the code and add the slashes without the risk of duplicating the effects of `safe_value($var)` and stacking the slashes.

I also think I need to refactor this code to handle magic quotes if it is turned on...

**Comment by ghost** [comment]
It appears that safe_value already takes magic quotes into account.  

Code is ready for review.

**Pull request merged**
