### PR TITLE
Add Clear button in bayes_info.php

### PR DESCRIPTION
**Pull request by stefaweb**
Add a "Clear" button in Bayes Info. 

Allows to empty the database. When it becomes too old (and big) is becoming less effective.

068ab584-e2e7-11e6-8b82-3e50ad7a2379

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/435)

### CODE REVIEW

**Comment by stefaweb** [comment]
I've a problem of refresh of the table after pushing the delete button.

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
we should ask for confirmation here

**Comment by Skywalker-11** [comment]
*[mailscanner/bayes_info.php, line 130 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFZazYV94cpQjecpXE:-KbFZazYV94cpQjecpXF:bdhqtdc) ([raw file](https://github.com/mailwatch/1.2.0/blob/a11d3cf7b20e57d22fd8ca88d4998ded97908a4a/mailscanner/bayes_info.php#L130)):*
> ```PHP
>     echo '           <input type="hidden" name="clear" value="true">';
>     echo '           <br><br>';
>     echo '  </div></div></form></div>';
> ```

too many </div>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
*[mailscanner/bayes_info.php, line 130 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFZazYV94cpQjecpXE:-KbFZi59L7PLdmca0Pm8:b-4lzlyu) ([raw file](https://github.com/mailwatch/1.2.0/blob/a11d3cf7b20e57d22fd8ca88d4998ded97908a4a/mailscanner/bayes_info.php#L130)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

too many </div>
</blockquote></details>

* too many < / d i v>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
*[mailscanner/bayes_info.php, line 127 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbF_MDdVWuznASurYq8:-KbF_MDdVWuznASurYq9:b8m4ep3) ([raw file](https://github.com/mailwatch/1.2.0/blob/a11d3cf7b20e57d22fd8ca88d4998ded97908a4a/mailscanner/bayes_info.php#L127)):*
> ```PHP
>     echo '        <div style="margin: 5px">';
>     echo '           <br>';
>     echo '           <input type="submit" value="Clear Bayes Database">';
> ```

translations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mailscanner/bayes_info.php, line 127 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbF_MDdVWuznASurYq8:-KbFbP536iZWy_lVSRQI:bpca47t) ([raw file](https://github.com/mailwatch/1.2.0/blob/a11d3cf7b20e57d22fd8ca88d4998ded97908a4a/mailscanner/bayes_info.php#L127)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

translations
</blockquote></details>

will come later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[mailscanner/bayes_info.php, line 130 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFZazYV94cpQjecpXE:-KbFbZrXTN74SobCWwFC:b-7ql1td) ([raw file](https://github.com/mailwatch/1.2.0/blob/a11d3cf7b20e57d22fd8ca88d4998ded97908a4a/mailscanner/bayes_info.php#L130)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

* too many < / d i v>
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
The table with bayes infos is still not refreshed after click on Clear button.

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
I get `bayes: expire_old_tokens: locker: safe_lock: cannot create lockfile /etc/MailScanner/bayes/bayes.mutex: Permission denied` in webserver log but the return code of the command is 0 (success) when using 
`passthru(SA_DIR . 'sa-learn -p ' . SA_PREFS . ' --force-expire', $return);`

So how do we know if it is successful?

**Comment by stefaweb** [comment]
> , $return

I added it. I got "0" if I print $return.

I don't have error message as you but I'm using bayes in mysql...

I know that the command was successful as after a forced reload of the page, the time is new.



---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-:-KbFg9OYqQzuWBP1iNHE:bk5htr3)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Works with refresh.

What is the best solution to add a confirmation message?

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
*[mailscanner/bayes_info.php, line 139 at r5](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFuFagGSWVZ1WgUF_J:-KbFuFagGSWVZ1WgUF_K:b-z3ey7a) ([raw file](https://github.com/mailwatch/1.2.0/blob/eb0d148a9516c9166f3769e8340ef4a0043a8e74/mailscanner/bayes_info.php#L139)):*
> ```PHP
>             passthru(SA_DIR . 'sa-learn -p ' . SA_PREFS . ' --force-expire', $return);
>             if ($return == 0) {
>                 audit_log("Wipe out existing SpamAssassin Bayes Database");
> ```

should be wiped out because it already happened

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mailscanner/bayes_info.php, line 139 at r5](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFuFagGSWVZ1WgUF_J:-KbFwwnbTcRkNNwOfDn_:be6ngh5) ([raw file](https://github.com/mailwatch/1.2.0/blob/eb0d148a9516c9166f3769e8340ef4a0043a8e74/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

should be wiped out because it already happened
</blockquote></details>

No agree. If not 0, sa-learn --clear not done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
*[mailscanner/bayes_info.php, line 139 at r5](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFuFagGSWVZ1WgUF_J:-KbFzSzMJ33NJaJRQCxP:b-gt98s6) ([raw file](https://github.com/mailwatch/1.2.0/blob/eb0d148a9516c9166f3769e8340ef4a0043a8e74/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

No agree. If not 0, sa-learn --clear not done.
</blockquote></details>

yeah but you already tested if it is zero when you do the log :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mailscanner/bayes_info.php, line 139 at r5](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFuFagGSWVZ1WgUF_J:-KbG-eEJMtW3nICb3uYj:buu0zkj) ([raw file](https://github.com/mailwatch/1.2.0/blob/eb0d148a9516c9166f3769e8340ef4a0043a8e74/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

yeah but you already tested if it is zero when you do the log :-)
</blockquote></details>

sorry, I don't understand the problem. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
*[mailscanner/bayes_info.php, line 139 at r5](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFuFagGSWVZ1WgUF_J:-KbG30w-TqBz5D6yCExQ:b-nthkln) ([raw file](https://github.com/mailwatch/1.2.0/blob/eb0d148a9516c9166f3769e8340ef4a0043a8e74/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

sorry, I don't understand the problem. 
</blockquote></details>

just a typo that it should be "Wiped out existing SpamAssassin Bayes Database"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
*[mailscanner/languages/de.php, line 523 at r6](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbG54NHh04_sCvzrmh2:-KbG54NHh04_sCvzrmh3:bgzgbfy) ([raw file](https://github.com/mailwatch/1.2.0/blob/52ff24f719ec4049c498d01e642e1b5b46237895/mailscanner/languages/de.php#L523)):*
> ```PHP
>     'cleardbbayes18' => 'Clear Bayes Database',
>     'auditlogwipe18' => 'Wiped out existing SpamAssassin Bayes Database',
>     'error18' => 'Error:',
> ```

'cannotfind18' => 'Fehler: Konnte Datei nicht finden',
'cleardbbayes18' => 'Bayes-Datenbank leeren',
'auditlogwipe18' => 'Die vorhandene SpamAssassin Bayes-Datenbank wurde geleert',
'error18' => 'Fehler:',

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
For the "confirmation", I don't now what to do. A new windows? A message with a new button?

If you have an idea with a piece of code, I take it. ;)

**Comment by Skywalker-11** [comment]
Reviewed 1 of 2 files at r7.
Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[mailscanner/bayes_info.php, line 127 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbF_MDdVWuznASurYq8:-KbGBrVpGCbjiHuZsRY-:bb7f2mf) ([raw file](https://github.com/mailwatch/1.2.0/blob/a11d3cf7b20e57d22fd8ca88d4998ded97908a4a/mailscanner/bayes_info.php#L127)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

will come later
</blockquote></details>

done

---

*[mailscanner/bayes_info.php, line 139 at r5](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbFuFagGSWVZ1WgUF_J:-KbGBtkjE51pQqXa1eDS:bb7f2mf) ([raw file](https://github.com/mailwatch/1.2.0/blob/eb0d148a9516c9166f3769e8340ef4a0043a8e74/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

just a typo that it should be "Wiped out existing SpamAssassin Bayes Database"
</blockquote></details>

done

---

*[mailscanner/languages/de.php, line 523 at r6](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbG54NHh04_sCvzrmh2:-KbGBv8IvdsyB_zyeAr9:bb7f2mf) ([raw file](https://github.com/mailwatch/1.2.0/blob/52ff24f719ec4049c498d01e642e1b5b46237895/mailscanner/languages/de.php#L523)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

'cannotfind18' => 'Fehler: Konnte Datei nicht finden',
'cleardbbayes18' => 'Bayes-Datenbank leeren',
'auditlogwipe18' => 'Die vorhandene SpamAssassin Bayes-Datenbank wurde geleert',
'error18' => 'Fehler:',

</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 5 of 7 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
we have something at the user_manager (line 48-55):
```
<!--
        function delete_user(id) {
            var yesno = confirm(" Soll der Benutzer tatsächlich gelöscht werden " + id + "?");
            if (yesno === true) {
                window.location = "?action=delete&id=" + id;
            } else {
                return false;
            }
        }
```

it is triggered by line 335:
`<a href=\"javascript:delete_user(\'',username,'\')\">" . safe_value(__('delete12')) . "</a>`

**Comment by Skywalker-11** [comment]
Reviewed 4 of 7 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Thanks. Will work on this later.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-:-KbGDNHwGkVeHB4-yd5t:b-89snng)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Do not publish. Not finished.

**Comment by stefaweb** [comment]
Bug: 
After page load, if we click on Clear button, the screen refresh but bayes values on table are not updated. If we click a second time, bayes values are updated.
We have two entries in Audit Log.

**Comment by Skywalker-11** [comment]
when you move the new part in front of line 51 it should work the first time

**Comment by Skywalker-11** [comment]
But theres still the problem with file based bayes filter. 
Is it possible that mailscanner is locking that file and so it doesn't work?

**Comment by Skywalker-11** [comment]
*[mailscanner/bayes_info.php, line 139 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbGYEaR03IRenWbjfbu:-KbGYEaR03IRenWbjfbv:b-cxaszp) ([raw file](https://github.com/mailwatch/1.2.0/blob/df6fce378ec3956ea395f69433e11364c3279031/mailscanner/bayes_info.php#L139)):*
> ```PHP
>         } else {
>             // Using --force-expire instead of --clear for testing purpose - TO REMOVE BEFORE PUBLISHING IT
>             passthru(SA_DIR . 'sa-learn -p ' . SA_PREFS . ' --force-expire', $return);
> ```

remember to remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/bayes_info.php, line 139 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbGYEaR03IRenWbjfbu:-KbGhWO7FRjbZ2Dd3S3O:b-d7bhn0) ([raw file](https://github.com/mailwatch/1.2.0/blob/df6fce378ec3956ea395f69433e11364c3279031/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

remember to remove
</blockquote></details>

will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/bayes_info.php, line 139 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbGYEaR03IRenWbjfbu:-KbGhuqmYlaAjiKKLSrD:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/df6fce378ec3956ea395f69433e11364c3279031/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

will do
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
try without the -p ' . SA_PREFS . ' to see

**Comment by stefaweb** [comment]
Reviewed 7 of 7 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 7 of 7 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
de.php:

'clearmessage18' => 'Are you sure you want to clear the Bayes database?',

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
de.php

`'clearmessage18' => 'Sind sie sicher, dass die Bayes-Datenbank geleert werden soll?',`

**Comment by stefaweb** [comment]
Ok for me.

I would have preferred to have the button clear below the table but I do not have time to look for why it does not refresh when it is below the table.

**Comment by stefaweb** [comment]
Reviewed 2 of 2 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
the problem is that you ran the the sa-learn for generating the bayes infos BEFORE clearing it 
[https://github.com/stefaweb/1.2.0/blob/a2b9d9c842efce5167636a0514621a0c62e02c76/mailscanner/bayes_info.php#L55](https://github.com/stefaweb/1.2.0/blob/a2b9d9c842efce5167636a0514621a0c62e02c76/mailscanner/bayes_info.php#L55) you generate the table with bayes stats.

[https://github.com/stefaweb/1.2.0/blob/a2b9d9c842efce5167636a0514621a0c62e02c76/mailscanner/bayes_info.php#L139](https://github.com/stefaweb/1.2.0/blob/a2b9d9c842efce5167636a0514621a0c62e02c76/mailscanner/bayes_info.php#L139) after that you clear the bayes db here


To display the button below just put this after the switch-cases

```
 +    echo '  <div style="text-align: center; ">'. "\n";
 +    echo '     <form method="post" action="bayes_info.php" onsubmit="return confirm(\'' . __('clearmessage18') . '\');" >'. "\n";
 +    echo '           <input type="submit" value="' . __('cleardbbayes18') . '">'. "\n";
 +    echo '           <input type="hidden" name="clear" value="true">'. "\n";
 +    echo '           <br>'. "\n";
 +    echo '     </form>'. "\n";
 +    echo '  </div>'. "\n";
```

**Comment by stefaweb** [comment]
Yes better with the button below.
Thanks.
I tried with --clear. Works on my side.

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r17.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/bayes_info.php, line 139 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbGYEaR03IRenWbjfbu:-KbJsw0IjanTRnNyfGuy:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/df6fce378ec3956ea395f69433e11364c3279031/mailscanner/bayes_info.php#L139)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
capture d ecran 2017-01-25 a 10 13 13

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r18.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r19.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Should be ready to push.

**Comment by Skywalker-11** [comment]
*[mailscanner/languages/en.php, line 524 at r19](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbKrARbSwZGRncImeVY:-KbKrARbSwZGRncImeVZ:b-al456m) ([raw file](https://github.com/mailwatch/1.2.0/blob/e8e36ded8ed578d6683e3d68a245e86932eff981/mailscanner/languages/en.php#L524)):*
> ```PHP
>     'auditlogwipe18' => 'Wiped out existing SpamAssassin Bayes Database',
>     'error18' => 'Error:',
>     'clearmessage18' => 'Sind sie sicher, dass die Bayes-Datenbank geleert werden soll?',
> ```

thats german to english :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
*[mailscanner/languages/en.php, line 524 at r19](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbKrARbSwZGRncImeVY:-KbKrXTrvMK0Rm6PyD8K:b9mbdm0) ([raw file](https://github.com/mailwatch/1.2.0/blob/e8e36ded8ed578d6683e3d68a245e86932eff981/mailscanner/languages/en.php#L524)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

thats german to english :-)
</blockquote></details>

* thats german not english 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 2 of 2 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/languages/en.php, line 524 at r19](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbKrARbSwZGRncImeVY:-KbKwqrjwP_fC1x8VBFa:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/e8e36ded8ed578d6683e3d68a245e86932eff981/mailscanner/languages/en.php#L524)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

* thats german not english 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
Reviewed 4 of 7 files at r11, 1 of 1 files at r19, 2 of 2 files at r20.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by endelwar** [comment]
Reviewed 4 of 7 files at r11, 1 of 1 files at r19, 2 of 2 files at r20.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[mailscanner/bayes_info.php, line 52 at r20](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbkbPt5YDzJNmTTClPS:-KbkbPt5YDzJNmTTClPT:b-3v0fav) ([raw file](https://github.com/mailwatch/1.2.0/blob/1a04e663ca2b8b74498943680217b3fa69d5d86e/mailscanner/bayes_info.php#L52)):*
> ```PHP
> 
> // Clear Bayes database
> if ($_SESSION['user_type'] == 'A') {
> ```

Always use strict comparison (`===`)

---

*[mailscanner/bayes_info.php, line 146 at r20](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbkbrRzP95OnHGb-SMl:-KbkbrRzP95OnHGb-SMm:bwir0uv) ([raw file](https://github.com/mailwatch/1.2.0/blob/1a04e663ca2b8b74498943680217b3fa69d5d86e/mailscanner/bayes_info.php#L146)):*
> ```PHP
> 
> // Clear button
> if ($_SESSION['user_type'] == 'A') {
> ```

strict also here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[mailscanner/bayes_info.php, line 52 at r20](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbkbPt5YDzJNmTTClPS:-KbkmOLgrUe0m2dAvcOf:b32wtd) ([raw file](https://github.com/mailwatch/1.2.0/blob/1a04e663ca2b8b74498943680217b3fa69d5d86e/mailscanner/bayes_info.php#L52)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary><blockquote>

Always use strict comparison (`===`)
</blockquote></details>

ok

---

*[mailscanner/bayes_info.php, line 146 at r20](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbkbrRzP95OnHGb-SMl:-KbkmPZtbJAC8Lt1UKjQ:b32wtd) ([raw file](https://github.com/mailwatch/1.2.0/blob/1a04e663ca2b8b74498943680217b3fa69d5d86e/mailscanner/bayes_info.php#L146)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary><blockquote>

strict also here
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r21.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mailscanner/bayes_info.php, line 52 at r20](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbkbPt5YDzJNmTTClPS:-Kbkn58hr1UMmJ-S6VLE:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/1a04e663ca2b8b74498943680217b3fa69d5d86e/mailscanner/bayes_info.php#L52)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---

*[mailscanner/bayes_info.php, line 146 at r20](https://reviewable.io:443/reviews/mailwatch/1.2.0/435#-KbkbrRzP95OnHGb-SMl:-Kbkn4PfcvfkY5tmFUiC:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/1a04e663ca2b8b74498943680217b3fa69d5d86e/mailscanner/bayes_info.php#L146)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r22.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Reviewed 6 of 6 files at r23.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by stefaweb** [comment]
Ready to merge.

**Comment by endelwar** [comment]
Has the code been tested with file based bayes?

**Comment by stefaweb** [comment]
No news from @Skywalker-11 from this.

**Comment by stefaweb** [comment]
Reviewed 6 of 6 files at r24.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/435)*

**Comment by Skywalker-11** [comment]
Haven't look at it again yet

**Comment by Skywalker-11** [comment]
` You an use --force-expire insteaf of --clear to test the routine`
should be 
` You can use --force-expire instead of --clear to test the routine`

**Comment by Skywalker-11** [comment]
I don't have much experience with bayes but the command is run without errors now and "Last Expiry" is reset

**Comment by endelwar** [comment]
I use mysql bayes too, I don't have any test system available with file based bayes. I'm going to merge this anyway, and test as soon as I can install a new dev vm

**Pull request merged**
