### PR TITLE
Add fa-info-circle to replace #

### PR DESCRIPTION
**Pull request by asuweb**
Fixes issue #629

### CODE REVIEW

**Comment by endelwar** [comment]
I like the idea, but I don't like the full font-awesome inclusion.
I've made a svg version of the icon, with 2 png image fallback (blue and green) that can be used like this:
```html
<img src="info-circle.svg" onerror="this.src='info-circle.png'; this.onerror=null;">
```
[info-circle.zip](https://github.com/mailwatch/1.2.0/files/847585/info-circle.zip)

Can you work on these images?

**Comment by asuweb** [comment]
Will do

**Comment by asuweb** [comment]
@endelwar - I've changed it to use css background images instead as it was easier to apply hover effects

**Comment by endelwar** [comment]
please remove the font files, so I can merge

**Comment by asuweb** [comment]
Done :)

**Pull request merged**
