### PR TITLE
Fix long queue id validation

### PR DESCRIPTION
**Pull request by ghost**
Minor fix for postfix long queue id validation

### CODE REVIEW

**Comment by Skywalker-11** [comment]
Can you explain where `\.[A-F0-9]{5}` comes from?

**Comment by ghost** [comment]
@Skywalker-11 

https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Postfix.pm#L1878-L1884

I think this was an oversight when the long queue ID support was added a while back.  It is still appending the 5 character key to the ID.  There should be logic here to only do this to short queue IDs.  Nonetheless, the weird looking long queue ID + 5 char key should be permitted since it has persisted in recent versions of MailScanner.

**Comment by ghost** [comment]
Fixing in my working branch. 

https://github.com/shawniverson/v5/commit/77e4117798747c4b6c94048de66e5bf0ce6a4018

**Comment by ghost** [comment]
Another modification to fix

https://github.com/shawniverson/v5/commit/f1782935727b9247111f0f6246f1d81c6176e4a2

**Pull request merged**
