### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by rafaelbsd**
Hi, there. Just created this branch to merge to master branch of MailWach.

### CODE REVIEW

**Comment by endelwar** [comment]
Can you try to [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) the commits into one? It should be easier to merge automatically

**Comment by endelwar** [comment]
or better: start with a clean copy of master, create a new branch, copy over your modified files, and create a single commit

**Comment by stefaweb** [comment]
I've done this. Copied all my modified file outside git, created a branch from a fresh master, and copied back the files inside this branch.

And you got this.

capture d ecran 2015-06-24 a 18 44 25

**Comment by endelwar** [comment]
@stefaweb there are 4 commits in that PR (https://github.com/mailwatch/1.2.0/pull/192/commits)

**Comment by stefaweb** [comment]
@endelwar 
The 3 others are very small. You can may be do them by hand?
Its so boring to do the merge again. ;-)

**Comment by endelwar** [comment]
just do a squash http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

**Pull request closed without merging**
