### PR TITLE
New language files v0.3.12 + viewpart.php (merge it first)

### PR DESCRIPTION
**Pull request by stefaweb**
New language files v0.3.12

Please be careful when you merge. I spent half an hour to check the
files due to wrong count of words/lines.

A good tips: Go to the last line of each file and look for the last
line number and compare.

When you add an entry, add it in all languages files.

### CODE REVIEW

**Comment by Skywalker-11** [comment]
de:
'title58' => 'Anzeige von Quarantäne-E-Mails',

**Comment by stefaweb** [comment]
Thansk @Skywalker-11 

Ready to merge.

**Comment by stefaweb** [comment]
New language files v0.3.12  …
Please be careful when you merge. I spent half an hour to check the
files due to wrong count of words/lines.
A good tips: Go to the last line of each file and look for the last
line number and compare.

Ready to merge.

**Comment by stefaweb** [comment]
Missing for de.php:

```
    'count44' => 'Count',
    'size44' => 'Size',
```

**Comment by stefaweb** [comment]
And 99 in de.php:

`'missing_conf_entries' => 'The following conf.php entries are missing, check compare your conf.php with conf.php.example.',`

**Comment by Skywalker-11** [comment]
Actually count44 and size44 shouldn't be in en.php 😄 

99 is in develop but has a typo. Needs to be 
`'missing_conf_entries' => 'Die folgenden Einträge der conf.php fehlen. Vergleichen Sie die conf.php mit conf.php.example',
`

**Comment by stefaweb** [comment]
> Actually count44 and size44 shouldn't be in en.php 😄

Already in develop!

**Pull request merged**
