### PR TITLE
Apache config files for MailWatch

### PR DESCRIPTION
**Pull request by stefaweb**
Basic Apache configuration files and doc.

### CODE REVIEW

**Comment by stefaweb** [comment]
Do we need "short_open_tag = On"?
I don't remember.

**Comment by Skywalker-11** [comment]
we always use `<?php` to start php part so there shouldn't be a need for short_open_tag

**Comment by stefaweb** [comment]
Ready to merge.

**Comment by asuweb** [comment]
@stefaweb - these files are specific to Debian based systems, and are not compatible with other *nix systems, such as red-hat based variants.

**Comment by stefaweb** [comment]
I don't have RedHat .rpm server.
If you have one, I can add the config and doc. 
And add directory in tools/Apache for Debian, RedHad and others if needed.

**Comment by Skywalker-11** [comment]
@asuweb do you mean the mod_php part? If that's the case we may should split apache and php configuration. 

@stefaweb we should add a `Require all-granted`  for apache 2.4 or for version 2.2 
```
Order allow,deny
Allow from all
```

**Comment by asuweb** [comment]
@Skywalker-11 - sorry, no the actual config will probably work, but the instructions won't.  

Do we want to make this a global config or a vhost?  Personally I use a vhost for the mailwatch interface, rather than a global config.

The proposed install script (#453) should probably take care of this aspect as well

**Comment by asuweb** [comment]
For redhat based systems (redhat / centos / fedora)

The apache dirs are 
 `/etc/httpd/`
`/etc/httpd/conf.d/`

The `a2en...` commands do not exist

`service httpd restart`

**Comment by endelwar** [comment]
This should belong to https://github.com/mailwatch/mailwatch-docs, in a dedicated section that talks about server configuration and other tips related to MailWatch

**Comment by stefaweb** [comment]
I agree. There are dozens of ways to do it. I can not generate vhost configs for all systems and way to do.

Better to close this PR.

**Comment by stefaweb** [comment]
Close this. 
Better in MailWatch online doc.

**Pull request closed without merging**
