### PR TITLE
added css class to hide elements for printing (#400)

### PR DESCRIPTION
**Pull request by Skywalker-11**
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/407)

### CODE REVIEW

**Comment by yogurtnaturalny** [comment]
Hi, I would like to know when this option will be added to your awesome UI, please?

**Comment by endelwar** [comment]
Hi, it was added on 19 Jan 2017, so it is present from release 1.2.0-rc5 and above

**Comment by yogurtnaturalny** [comment]
Hi, thank you for that, maybe it is my fault but I can't get it right??? When I'm on email detail page and press Ctrl - P for printing this still not show up as was here #400 Am I doing something wrong?

**Comment by Skywalker-11** [comment]
@yogurtnaturalny
Which version of MailWatch do you use? Can you give a screenshot of the page?

**Comment by yogurtnaturalny** [comment]
MailWatch 1.2.2 
And apologise, I can't provide  screenshot, however, I'm on normal page https://mymailscanserver.com/detail.php?token=XXXX and this one I would like to print as report of spam to provide to 3rd party anti-spam system ( so we all can benefit  from it :-) )

**Comment by yogurtnaturalny** [comment]
Hello

I think I found a problem, FireFox is very special and got special needs as Chrome works well, thank you for have a look into this and add this feature to your UI

**Comment by Skywalker-11** [comment]
Which firefox version do you use? This what i get in firefox 53.0.3 on Windows for printing:
image

**Comment by yogurtnaturalny** [comment]
It was Debian 8 FF 45 so maybe that why :-( apologies

**Comment by Skywalker-11** [comment]
Some actions and links were not hidden when printing. The PR corrects this.

**Pull request merged**
