### PR TITLE
Adds the ability for domain admins to create/edit/delete user of the same domain (#276)

### PR DESCRIPTION
**Pull request by Skywalker-11**
This gives the domain admins the ability to create/edit/delete user of the same domain (Request #276)
Same domain means:
- Domain admin `admin@domain1` can manage users with usernames `...@domain1` and create new users for that but not users without domain eg. `user1`, `user2` 
- Domain admin `admin1` (no mail -> without domain) can change/add users that also have no domains eg `user1`, `user2` but not `user3`@domain

The domain admins can also grant users domain admin permissions for the same domain but are unable to give full admin permissions to users. They can not move users to other domains.

Users with full admin permissions can still do anything.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/418)

### CODE REVIEW

**Comment by Skywalker-11** [comment]
The language file is version 0.3.9 under the assumption that #410 will be applied before. and then included here

**Comment by Skywalker-11** [comment]
includes #410

**Comment by stefaweb** [comment]
To replace in fr.php

```

    'erroreditnodomainforbidden12' => 'Erreur : vous n\'avez pas les autorisations pour modifier les utilisateurs sans domaine',
    'erroreditdomainforbidden12' => 'Erreur : vous n\'avez pas les autorisations pour modifier les utilisateurs du domaine %s',
    'errortonodomainforbidden12' => 'Erreur : vous n\'avez pas les autorisations pour supprimer le domaine des utilisateurs',
    'errortodomainforbidden12' => 'Erreur : vous n\'avez pas les autorisations pour assigner des utilisateurs au domaine %s',
    'errortypesetforbidden12' => 'Erreur : vous ne disposez pas des autorisations nécessaires pour attribuer des droits d\'administrateur aux utilisateurs',
    'errordeletenodomainforbidden12' => 'Erreur : vous n\'avez pas les autorisations pour supprimer des utilisateurs sans domaine',
    'errordeletedomainforbidden12' => 'Erreur : vous n\'avez pas les permissions pour supprimer les utilisateurs du domaine %s',
    'errorcreatenodomainforbidden12' => 'Erreur : vous n\'avez pas les autorisations pour ajouter des utilisateurs sans domaine',
    'errorcreatedomainforbidden12' => 'Erreur : vous n\'avez pas les autorisations pour ajouter des utilisateurs au domaine %s',

```

**Comment by stefaweb** [comment]
Again to do:

In all language files add:

English:
'retypepassword12' => 'Confirm Password:',

French:
'retypepassword12' => 'Confirmez le mot de passe :',

Update second password12 in user_manager.php with new retypepassword12 value.

**Comment by stefaweb** [comment]
The script should be checked. Many errors between username, fullname, user, etc...

**Comment by stefaweb** [comment]
And with ":" and without ":".

**Comment by stefaweb** [comment]
From an ergonomic point of view, the "username" field should not be able to be modified in Edit mode.

**Comment by asuweb** [comment]
@Skywalker-11 - Could you explain the purpose of the second part of the logic?  I know people use the system in different ways, but I can't see a use for a user without domain?

**Comment by Skywalker-11** [comment]
This could be used for example if we later have multiple user backend and some may do not have a domain; or to differentiate them from local users. 

Eg you can have ldap backends for multiple domains each with its own domain admins and more accounts without domain for users with admins permissions (organization hosting mailwatch). There we can assure that the domain admins can't see/edit that users

**Comment by Skywalker-11** [comment]
> We must stay on the same page not go to user list.

@stefaweb can you explain that?

**Comment by stefaweb** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/user_manager.php, line 104 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/418#-Kb5siY3S6Sr6t1MV8B4:-Kb5siY3S6Sr6t1MV8B5:b-ouvq9v) ([raw file](https://github.com/mailwatch/1.2.0/blob/544d08c26639f8c74f975a3b367c0e32fe660541/mailscanner/user_manager.php#L104)):*
> ```PHP
>                     echo " <TR><TD CLASS=\"heading\">" . __('username0212') . " <BR></TD><TD><INPUT TYPE=\"TEXT\" NAME=\"username\"></TD></TR>\n";
>                     echo " <TR><TD CLASS=\"heading\">" . __('name12') . "</TD><TD><INPUT TYPE=\"TEXT\" NAME=\"fullname\"></TD></TR>\n";
>                     echo " <TR><TD CLASS=\"heading\">" . __('password12') . "</TD><TD><INPUT TYPE=\"PASSWORD\" ID=\"password0\" NAME=\"password\"></TD></TR>\n";
> ```

May be better to use:
password0 -> password
password1 -> retypepassword

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by Skywalker-11** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/user_manager.php, line 104 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/418#-Kb5siY3S6Sr6t1MV8B4:-Kb6IyUDuatpKx0OhU5J:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/544d08c26639f8c74f975a3b367c0e32fe660541/mailscanner/user_manager.php#L104)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

May be better to use:
password0 -> password
password1 -> retypepassword
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
For fr.php:

`'userexists12' => 'L\'utilisateur existe déjà avec le nom d'utilisateur %s',`

**Comment by stefaweb** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by Skywalker-11** [comment]
should be ready for merge

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[mailscanner/user_manager.php, line 357 at r7](https://reviewable.io:443/reviews/mailwatch/1.2.0/418#-KbLf4sfAH3qAzMTU86U:-KbLf4sgqOOVXGQXMdKL:bcsahiv) ([raw file](https://github.com/mailwatch/1.2.0/blob/3383a8b0744ee82ad852ce5fc2f29cf1a3788d74/mailscanner/user_manager.php#L357)):*
> echo '<br>'."\n";
Add a br

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by Skywalker-11** [comment]
*[mailscanner/user_manager.php, line 357 at r7](https://reviewable.io:443/reviews/mailwatch/1.2.0/418#-KbLf4sfAH3qAzMTU86U:-KbLmsjEnbz4eozckV6-:b29ja3r) ([raw file](https://github.com/mailwatch/1.2.0/blob/3383a8b0744ee82ad852ce5fc2f29cf1a3788d74/mailscanner/user_manager.php#L357)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

> echo '<br>'."\n";
Add a br
</blockquote></details>

a second br?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/user_manager.php, line 357 at r7](https://reviewable.io:443/reviews/mailwatch/1.2.0/418#-KbLf4sfAH3qAzMTU86U:-KbOyb1uWc5OXnCpiFaU:butn0hx) ([raw file](https://github.com/mailwatch/1.2.0/blob/3383a8b0744ee82ad852ce5fc2f29cf1a3788d74/mailscanner/user_manager.php#L357)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

a second br?
</blockquote></details>

Was not clear yesterday.

I just want this if not already done.



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/user_manager.php, line 357 at r7](https://reviewable.io:443/reviews/mailwatch/1.2.0/418#-KbLf4sfAH3qAzMTU86U:-Kb_tNeVJwWhJ2B_YUIe:bb7g85b) ([raw file](https://github.com/mailwatch/1.2.0/blob/3383a8b0744ee82ad852ce5fc2f29cf1a3788d74/mailscanner/user_manager.php#L357)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

Was not clear yesterday.

I just want this if not already done.



</blockquote></details>

fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by Skywalker-11** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/user_manager.php, line 357 at r7](https://reviewable.io:443/reviews/mailwatch/1.2.0/418#-KbLf4sfAH3qAzMTU86U:-Kba6WEwle4HngruykZ_:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/3383a8b0744ee82ad852ce5fc2f29cf1a3788d74/mailscanner/user_manager.php#L357)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

fine
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Reviewed 8 of 8 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by stefaweb** [comment]
Reviewed 8 of 8 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/418)*

**Comment by Skywalker-11** [comment]
ready for merge

**Pull request merged**
