### PR TITLE
Enhanced session expire handling

### PR DESCRIPTION
**Pull request by shawniverson**
Fixes for #662 and #708

-- Reduces the session duration to max 5 minutes for all

-- Restarts session count down on user interaction or page refresh using garbage collection technique

-- If STATUS_REFRESH + 60 > 300 then use STATUS_REFRESH + 60 instead to allow for successful page refresh with sufficient headroom.

-- Keeps login page fresh, 1 minute of inactivity will refresh page, unless user is currently typing in fields

### CODE REVIEW

**Comment by stefaweb** [comment]
Just to clarify for me.

If status refresh is 30 seconds, the system will work?

**Comment by shawniverson** [comment]
Yes

**Comment by stefaweb** [comment]
Good news all this work. I'll test as soon the PR is merged.

**Comment by shawniverson** [comment]
a.k.a. The fixes for @stefaweb that I hope will make her very happy 😄

**Comment by stefaweb** [comment]
Happy days !
23°C today in Paris!

**Comment by shawniverson** [comment]
One caveat to this approach is that garbage collection runs on every session_start().  I'm not seeing a significant impact here, be a real world test would be someone who has a lot of users using MailWatch concurrently.

**Comment by stefaweb** [comment]
> will make her very happy

will make `him` very happy  😉

**Comment by endelwar** [comment]
This should settle the session issues

**Pull request merged**
