### PR TITLE
Removes HTML5 datetime-local due to browser issues.

### LINKED ISSUE #479: TODO and BUG: in rep_audit_log.php (datetime-local doesn't work with Safari and Firefox)
- remove the mailscanner logo
- move the button "apply" below
- add colon

capture d ecran 2017-02-05 a 09 38 51

### PR DESCRIPTION
**Pull request by asuweb**
Fixes #479

### CODE REVIEW

**Comment by stefaweb** [comment]
Could you center the button?
May be better look than stick to the left.

**Comment by asuweb** [comment]
The button looks centered to me - in terms of the row.

I've removed the logo

**Comment by stefaweb** [comment]
In fact, this is Filter to put on the left.

7f3e8baa-eb88-11e6-9acd-d49de70695a9

**Comment by asuweb** [comment]
Sorry @stefaweb, I'm not sure what you want changed?

**Comment by stefaweb** [comment]
Sorry not clear.

```
  <form action="rep_audit_log.php" method="GET" class="floatleft">
    <div class="mail table" id="auditFilters">
      <div class="caption head">' . __('filter33') . '</div>
      <div class="row"><div class="cell head">' . __('startdate33') . '</div><div class="cell data"><input name="startDate" type="text" placeholder="YYYY-MM-DD" value="' . $startDate . '"/></div></div>
      <div class="row"><div class="cell head">' . __('enddate33') . '</div><div class="cell data"><input name="endDate" type="text" placeholder="YYYY-MM-DD" value="' . $endDate . '"/></div></div>
      <div class="row"><div class="cell head">' . __('user33') . '</div><div class="cell data"><input name="username" type="text" value="' . $username . '"/></div></div>
      <div class="row"><div class="cell head">' . __('ipaddress33') . '</div><div class="cell data"><input name="ipaddress" type="text" value="' . $ipaddress . '"/></div></div>
      <div class="row"><div class="cell head">' . __('action33') . '</div><div class="cell data"><input name="actions" type="text" value="' . $actions . '"/></div></div>
      <div class="row"><div class="cell head"></div><div class="cell head"><button type="submit">' . __('applyfilter33') . '</button></div></div>
    </div>
  </form>
```
I corrected an eror on placeholder.

**Pull request merged**
