### PR TITLE
New version of upgrade.php

### PR DESCRIPTION
**Pull request by stefaweb**
With new schema form create.sql

### CODE REVIEW

**Comment by stefaweb** [comment]
Closed. Did a mistake.

**Comment by endelwar** [comment]
As said in the past, you should keep your fork (stefaweb/1.2.0) in sync with upstream (mailwatch/1.2.0).
On your repository do this:
- `git checkout develop`
- `git remote add upstream https://github.com/mailwatch/1.2.0.git`
- `git fetch upstream`
- `git rebase upstream/develop`
- fix code inconsistency if any (there should be none, if you work always on branch derived from develop)

This will speed up development and code merge 😜

**Comment by stefaweb** [comment]
Thanks for the remember, I so bad with git...  rebase was the command missing in my head.

I added comments and things to do in #419. Better than to do a new PR for upgrade.php

**Comment by endelwar** [comment]
I'm going to add this to documentation :)

**Comment by endelwar** [comment]
here it is: http://docs.mailwatch.org/dev/contributing.html

**Pull request closed without merging**
