### PR TITLE
Adjust login field width

### PR DESCRIPTION
**Pull request by shawniverson**
Login pane appears skewed after a recent commit.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/324)

### CODE REVIEW

**Comment by endelwar** [comment]
Shouldn't it be better to enlarge input field to 300px, to match left and right padding? Or are you seeing other imperfection?

**Comment by shawniverson** [comment]
That would also work.  I noticed that the original width was 308px.  Is there a reason it is now wider?  If so, that would make more sense.

**Comment by stefaweb** [comment]
Hello!
Sorry I'm busy but can you check with fr.php and de.php.

**Comment by endelwar** [comment]
It was enlarged for multi-language strings, some of them are longer that the English ones, see the French one down there.

schermata 2016-11-28 alle 12 43 59

**Comment by shawniverson** [comment]
Ok, I will revise PR to focus on the input boxes instead :)

**Comment by shawniverson** [comment]
Done, PR ready for review

**Pull request merged**
