### PR TITLE
Hide high spam and high mcp from regular users

### PR DESCRIPTION
**Pull request by shawniverson**
Very useful feature to hide offensive and suggestive emails detected by the system from regular users.

### CODE REVIEW

**Comment by endelwar** [comment]
Very good Shawn!
If you squash commits to https://github.com/shawniverson/1.2.0/commit/0b7555b75d005dc12d7f3a4feb2302dd31bb0b73 I can merge this asap

p.s.: look [here](http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages) for instruction on squashing

**Comment by endelwar** [comment]
also quarantine email should be affected by this PR

**Comment by shawniverson** [comment]
Messed something up when I squashed my commits....functions.php is a mess

**Comment by shawniverson** [comment]
I am going to close this and kill off my fork...I messed up

**Pull request closed without merging**
