### PR TITLE
Fixes issue #264 - 

### PR DESCRIPTION
**Pull request by asuweb**
This pull request fixes issue #264 

I've added a check in quarantine_report.php to check if the msg_id already exists in the autorelease table.  If it does, the release link will use the existing uid, instead of generating a new one.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/265)

### CODE REVIEW

**Comment by endelwar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/Cron_jobs/quarantine_report.php, line 377 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/265#-KPIXQ5a8JvJs2Hjv6nC:-KPIXQ5a8JvJs2Hjv6nD:bx29p7j) ([raw file](https://github.com/mailwatch/1.2.0/blob/04ed9311d09352989de99a5d2398ded4f7ee501e/tools/Cron_jobs/quarantine_report.php#L377)):*
> ```PHP
>         dbg(" === Error checking if msg_id already exists.....skipping....");
>     } else {
>         if (mysql_num_rows($result) == 0) {
> ```

use ===

---

*[tools/Cron_jobs/quarantine_report.php, line 379 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/265#-KPIXReBHQ87Lf4H24BV:-KPIXReBHQ87Lf4H24BW:bx29p7j) ([raw file](https://github.com/mailwatch/1.2.0/blob/04ed9311d09352989de99a5d2398ded4f7ee501e/tools/Cron_jobs/quarantine_report.php#L379)):*
> ```PHP
>         if (mysql_num_rows($result) == 0) {
>             return false;//msg_id not found,
>         } elseif (mysql_num_rows($result) == 1) {
> ```

use ===

---

*[tools/Cron_jobs/quarantine_report.php, line 402 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/265#-KPIX9dQ_pcpOqkB59No:-KPIX9dRVSuX3mtQewgv:b-hs6z6a) ([raw file](https://github.com/mailwatch/1.2.0/blob/04ed9311d09352989de99a5d2398ded4f7ee501e/tools/Cron_jobs/quarantine_report.php#L402)):*
> ```PHP
>             //Check if email already has an autorelease entry
>             $exists = check_auto_release($qitem);
>             if (!$exists) {
> ```

if ($exists === false) {

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/265)*

**Comment by asuweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/Cron_jobs/quarantine_report.php, line 377 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/265#-KPIXQ5a8JvJs2Hjv6nC:-KPJt6v7P5205IVApBFb:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/04ed9311d09352989de99a5d2398ded4f7ee501e/tools/Cron_jobs/quarantine_report.php#L377)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> use ===
</details>
Done.

---

*[tools/Cron_jobs/quarantine_report.php, line 379 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/265#-KPIXReBHQ87Lf4H24BV:-KPJt7rIGLCOxk_xScJ2:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/04ed9311d09352989de99a5d2398ded4f7ee501e/tools/Cron_jobs/quarantine_report.php#L379)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> use ===
</details>
Done.

---

*[tools/Cron_jobs/quarantine_report.php, line 402 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/265#-KPIX9dQ_pcpOqkB59No:-KPJt8JuGuBKN7EuGuvi:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/04ed9311d09352989de99a5d2398ded4f7ee501e/tools/Cron_jobs/quarantine_report.php#L402)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> if ($exists === false) {
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/265)*

**Comment by endelwar** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/265#-:-KPMZM-ZSi5zqR4eXXKJ:bnfp4nl)*

**Comment by endelwar** [comment]
Could you squash all commits into one? after that I'll merge PR

**Comment by asuweb** [comment]
I'm a git novice - I can work my way around the more simple stuff.  Happy to do it if you could give me a clue on how to do it?

**Pull request closed without merging**
