### PR TITLE
More update in language files

### PR DESCRIPTION
**Pull request by stefaweb**
'path04' => 'Path to message',

capture d ecran 2017-03-22 a 16 32 53

### CODE REVIEW

**Comment by Skywalker-11** [comment]
de: `Nachrichten-Pfad `

**Comment by stefaweb** [comment]
Need:

'errordeleteself12' => 'Error: You can not delete your own account!',

**Comment by stefaweb** [comment]
Needed for de.php

'errordeleteself12' => 'Error: You can not delete your own account!',

**Comment by Skywalker-11** [comment]
`Fehler: Sie können Ihren eigenen Account nicht löschen!`

**Comment by stefaweb** [comment]
Can be merged.

**Pull request merged**
