### PR TITLE
Changes in rep_total_mail_by_date.php and conf.php (and more)

### PR DESCRIPTION
**Pull request by stefaweb**
Added SHOW_MORE_INFO_ON_REPORT_GRAPH  …
Remove unknown_users, unresolveable and rbl columns when Postfix not
used.
in conf.php
in rep_total_mail_by_date.php

Corrected vertical margin in graph.

Show issue #173 for more info.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/342)

### CODE REVIEW

**Comment by stefaweb** [comment]
ALTER DATABASE `mailscanner` DEFAULT CHARACTER SET `utf8mb4` DEFAULT COLLATE `utf8mb4_unicode_ci`;

utf8mb4_unicode_ci OR utf8mb4_general_ci ?

**Comment by endelwar** [comment]
> utf8mb4_unicode_ci OR utf8mb4_general_ci ?

`utf8mb4_unicode_ci` is better that `utf8mb4_general_ci` even if it slower.
For this PR keep `_general_ci` and in a separate one convert everything to `_unicode_ci` (it's always better to handle multiple PR that do a single thing that one PR that does multiple corrections)

**Comment by stefaweb** [comment]
When I've a published PR but not yet validated by you. Each, time I add a new PR on my PC and sync, the things go directly in the current PR. It not create a new one. 
??

**Comment by endelwar** [comment]
It's beacuse you work on development branch and not on a new one.
Everytime you add to a branch that is used in a PR, that PR is automatically updated with new commits: you should sync your develop branch with MailWatch/1.2.0 one and then create a new branch (you can give it an eloquent name like "localization" or "fix_for_issue_123") and commit you changes to it, then create the PR from your branch to mailwatch's develop branch

**Pull request merged**
