### PR TITLE
All files changed from mailwatch/master

### PR DESCRIPTION
**Pull request by stefaweb**
New try. I hope this time it will be fine.
Many changes in core master branches.
Do not include translation changes or folder/files for translation.

### CODE REVIEW

**Comment by stefaweb** [comment]
Changes:
- added LOGO path in conf.php.example and changes done in corresponding files.
- layout changes in quarantine.php, other.php, sf_version.php
- removed duplicate PHP test in tools/Cron_jobs/quarantine_report.php
- changes in tools/Sendmail_relay/INSTALL
- changes in tools/Sendmail_relay/sendmail_relay.init
- background color change in login.php
- added clamav and spamassassin version in sf_version.php
- changes in INSTALL and UPGRADING
- modified footer function in functions.php (page footer and DEBUG for page_creation_timer)

**Comment by stefaweb** [comment]
Screen shot available here: https://github.com/mailwatch/1.2.0/issues/188

**Comment by stefaweb** [comment]
Changes over for this branch stefaweb:upgrade-to-master from my side.

**Comment by stefaweb** [comment]
Hello @endelwar!

Nothing more to add here. I just found a small notice in user_manager.php. See https://github.com/mailwatch/1.2.0/issues/193.

How do you plan to integrate my pull and the incoming translation pool from @rafaelbsd?

Cheers,

**Comment by endelwar** [comment]
Just add the right entry (be concise ;) ) in CHANGELOG.md to reflect your additions and fix

**Comment by stefaweb** [comment]
@endelwar 
Sorry 2 time, the line about logo.

**Comment by endelwar** [comment]
You should syncronize this PR with master (refer to [this](http://blog.michelemattioni.me/2013/01/29/what-do-i-do-when-my-pull-request-does-not-merge-automatically-in-master/) page for detailed instructions) to update with the new translation interface

**Comment by stefaweb** [comment]
New version coming.
Closing this one.

**Pull request closed without merging**
