### PR TITLE
Feature/checkconf.php

### PR DESCRIPTION
**Pull request by Skywalker-11**
adds a script to check if all necessary constants are defined in conf.php (#423)
mailscanner root folder can be passed as argument or defined in the script

The only problem with this approach is that the values of the constants cannot have line breaks in it. 
So QUARANTINE_MSG_BODY is breaking the config if it is missing
 

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/436)

### CODE REVIEW

**Comment by stefaweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/checkconf.php, line 32 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbHOkQQCKDQMiD8cDxN:-KbHOkQQCKDQMiD8cDxO:bd1x7w5) ([raw file](https://github.com/mailwatch/1.2.0/blob/59e93e1c3351a833659c0e691d7c57e3d04e7958/mailscanner/checkconf.php#L32)):*
> ```PHP
>  * Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
>  */
> $mailscannerRoot = "/var/www/mailscanner/";
> ```

Should be:
$mailscannerRoot = "/var/www/html/mailscanner/";

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/checkconf.php, line 32 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbHOkQQCKDQMiD8cDxN:-KbJyoF-uVb_qwKxh1PS:b32wtd) ([raw file](https://github.com/mailwatch/1.2.0/blob/59e93e1c3351a833659c0e691d7c57e3d04e7958/mailscanner/checkconf.php#L32)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

Should be:
$mailscannerRoot = "/var/www/html/mailscanner/";
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mailscanner/checkconf.php, line 1 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbK1Hz7l_2JE8bXqqzQ:-KbK1Hz7l_2JE8bXqqzR:b-xzpihi) ([raw file](https://github.com/mailwatch/1.2.0/blob/bb99b2f1570d36fbaa1615489b55ef62f851abe8/mailscanner/checkconf.php#L1)):*
> ```PHP
> #!/user/bin/php -q
> ```

Should be:
#!/usr/bin/php -q

+ chmod +x checkconf.php

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mailscanner/checkconf.php, line 42 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbK1wmCsdCJR0gwLmuJ:-KbK1wmCsdCJR0gwLmuK:b-hp2ynv) ([raw file](https://github.com/mailwatch/1.2.0/blob/bb99b2f1570d36fbaa1615489b55ef62f851abe8/mailscanner/checkconf.php#L42)):*
> ```PHP
> require($mailscannerRoot . "conf.php");
> 
> echo "Will check your conf.php if it contains all necessary constants" . PHP_EOL;
> ```

May be this will be better:

Checking your conf.php if it contains all necessary constants

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mailscanner/checkconf.php, line 42 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbK1wmCsdCJR0gwLmuJ:-KbKS161M4fp1O8dhCNB:b32wtd) ([raw file](https://github.com/mailwatch/1.2.0/blob/bb99b2f1570d36fbaa1615489b55ef62f851abe8/mailscanner/checkconf.php#L42)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

May be this will be better:

Checking your conf.php if it contains all necessary constants
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mailscanner/checkconf.php, line 1 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbK1Hz7l_2JE8bXqqzQ:-KbKgpIP_hBzx3Bn0UBD:bavbxyy) ([raw file](https://github.com/mailwatch/1.2.0/blob/bb99b2f1570d36fbaa1615489b55ef62f851abe8/mailscanner/checkconf.php#L1)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

Should be:
#!/usr/bin/php -q

+ chmod +x checkconf.php

</blockquote></details>

Have you see this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by Skywalker-11** [comment]
*[mailscanner/checkconf.php, line 1 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbK1Hz7l_2JE8bXqqzQ:-KbKly35YqdGIS9kS-5Q:bb7f2mf) ([raw file](https://github.com/mailwatch/1.2.0/blob/bb99b2f1570d36fbaa1615489b55ef62f851abe8/mailscanner/checkconf.php#L1)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

Have you see this one?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by Skywalker-11** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[mailscanner/checkconf.php, line 32 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbHOkQQCKDQMiD8cDxN:-KbKm9WG_p66JzcQV8zD:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/59e93e1c3351a833659c0e691d7c57e3d04e7958/mailscanner/checkconf.php#L32)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---

*[mailscanner/checkconf.php, line 42 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbK1wmCsdCJR0gwLmuJ:-KbKmAcm8OMoHE5ukZwi:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/bb99b2f1570d36fbaa1615489b55ef62f851abe8/mailscanner/checkconf.php#L42)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[mailscanner/checkconf.php, line 70 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLITJjHv9blB6vXzcT:-KbLITJjHv9blB6vXzcU:b-v5teya) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L70)):*
>  echo "Please review the values and adjust them to your needs" . PHP_EOL;

Add a <br>

---

*[mailscanner/checkconf.php, line 72 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLIPaL_Vuozf3audfP:-KbLIPaL_Vuozf3audfQ:bkvd314) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L72)):*
> echo "All necessary constants were found" . PHP_EOL;

Add a <br>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by Skywalker-11** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mailscanner/checkconf.php, line 70 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLITJjHv9blB6vXzcT:-KbLgbbsk093lE5gnaeS:byv9573) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L70)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

>  echo "Please review the values and adjust them to your needs" . PHP_EOL;

Add a <br>

</blockquote></details>

if called by command line br will not work

---

*[mailscanner/checkconf.php, line 72 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLIPaL_Vuozf3audfP:-KbLggnK5HXuvr4RIg-E:byv9573) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L72)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

> echo "All necessary constants were found" . PHP_EOL;

Add a <br>

</blockquote></details>

if called by command line br will not work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mailscanner/checkconf.php, line 72 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLIPaL_Vuozf3audfP:-KbLhcVJPV4eikR43C1I:b7c0deq) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L72)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

if called by command line br will not work
</blockquote></details>

sorry, new line as well /n/n

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by Skywalker-11** [comment]
*[mailscanner/checkconf.php, line 72 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLIPaL_Vuozf3audfP:-KbRJthvHogOTSjeYxT0:b-bus9m3) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L72)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

sorry, new line as well /n/n
</blockquote></details>

PHP_EOL adds the new line \ n on unix and \ r \ n for windows

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/checkconf.php, line 72 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLIPaL_Vuozf3audfP:-KbU2VWgjuEr5JlcJ4BQ:b-ga70od) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L72)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

PHP_EOL adds the new line \ n on unix and \ r \ n for windows
</blockquote></details>

Go this with last version:

antispam-dev:/home/xxxx/mailwatch-1.2.0-dev# ./checkconf.php

PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/xxxx/mailwatch-1.2.0-dev/checkconf.php:3) in /home/xxxx/mailwatch-1.2.0-dev/checkconf.php on line 38

Warning: Cannot modify header information - headers already sent by (output started at /home/xxxx/mailwatch-1.2.0-dev/checkconf.php:3) in /home/xxxx/mailwatch-1.2.0-dev/checkconf.php on line 38
Checking your conf.php if it contains all necessary constants
All necessary constants were found
antispam-dev:/home/xxxx/mailwatch-1.2.0-dev#

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by asuweb** [comment]
Shouldn't we also call this from upgrade.php, or at the least print instructions on the output of upgrade.php to run this script to update conf.php?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-:-KbZNKCFM5TzVvC81kNz:b-69r83o)*

**Comment by Skywalker-11** [comment]
done

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/checkconf.php, line 72 at r3](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-KbLIPaL_Vuozf3audfP:-KbZxLzfuLf_Js6Qo_p5:b58oi2n) ([raw file](https://github.com/mailwatch/1.2.0/blob/bc34d13dfe7df162f5bca7d74c9dbba54554c6ab/mailscanner/checkconf.php#L72)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

Go this with last version:

antispam-dev:/home/xxxx/mailwatch-1.2.0-dev# ./checkconf.php

PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/xxxx/mailwatch-1.2.0-dev/checkconf.php:3) in /home/xxxx/mailwatch-1.2.0-dev/checkconf.php on line 38

Warning: Cannot modify header information - headers already sent by (output started at /home/xxxx/mailwatch-1.2.0-dev/checkconf.php:3) in /home/xxxx/mailwatch-1.2.0-dev/checkconf.php on line 38
Checking your conf.php if it contains all necessary constants
All necessary constants were found
antispam-dev:/home/xxxx/mailwatch-1.2.0-dev#


</blockquote></details>

should be fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436#-:-KbZxTXgmblEv7VVHxDm:bb7f2mf)*

**Comment by asuweb** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by stefaweb** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/436)*

**Comment by endelwar** [comment]
Sorry @Skywalker-11 but I don't like very much the way the ckeck are made, in particular opening conf.php with fopen and editing of conf.php without sysadmin approval: the system administrators have to get their hands dirty and edit conf.php to their likings, just like the first time they installed MailWatch.

I came up with a working prototype that I'm going to commit

**Comment by Skywalker-11** [comment]
ok I will close it then

**Pull request closed without merging**
