### PR TITLE
Provides required field validation for user_manager

### PR DESCRIPTION
**Pull request by asuweb**
Adds required fields for username & password
Provides better style for error display

### CODE REVIEW

**Comment by stefaweb** [comment]
For fr.php

```
'erroruserreq12' => 'Nom d\'utilisateur nécessaire,
'errorpwdreq12' => 'Mot de passe nécessaire',
```

**Comment by stefaweb** [comment]
Found this:

`echo ' <TR><TD CLASS="heading">' . __('retypepassword12') . '</TD><TD><INPUT TYPE="PASSWORD" ID="retypepassword" NAME="password1"></TD></TR>'`

May be `NAME="retypepassword"` will be better?

**Comment by asuweb** [comment]
It works as it is, and it's been like that for years.  I can't really see any benefit in changing it

**Comment by stefaweb** [comment]
All this have been modified one month ago by @Skywalker-11 and me when we have localized and corrected some bugs there. The second name change for the 2 password fields have been forgotten. But it's just cosmetic.

**Pull request merged**
