### PR TITLE
use named virus regex; added avast regexp; fix nod32-1.99 virus regex

### PR DESCRIPTION
**Pull request by Skywalker-11**

### CODE REVIEW

**Comment by endelwar** [comment]
@Skywalker-11 is this code good to be merged?

**Comment by Skywalker-11** [comment]
It should work but there are cases where it might fail. These cases would probably also exist with the current code (see https://github.com/mailwatch/MailWatch/issues/1117#issuecomment-455282793)

**Comment by Skywalker-11** [comment]
Especially if multiple scanners are used or if a scanner marks multiple viruses in a single scan this introduces problems with this PR and also the current code.
This would require a change in MailScanner https://github.com/MailScanner/v5/issues/355

**Comment by endelwar** [comment]
It contains no harm, a fix and an additional AV, for me is a GO

**Pull request merged**
