### PR TITLE
Fixes to limit column size in mysql_status.php

### PR DESCRIPTION
**Pull request by stefaweb**
See #393

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/420)

### CODE REVIEW

**Comment by Skywalker-11** [comment]
I suggest that we create a css class containing that style information rather than hard code it in the html

**Comment by asuweb** [comment]
Agree, would be better with a class and the styles in style.css

**Comment by stefaweb** [comment]
I did an error and copied the wrong version. No need of class as I just added a str_replace().

**Comment by Skywalker-11** [comment]
I suggest using` preg_replace("/,[^\\s]/", ", ", $row[$f])` instead so we only add a whitespace where no space follows

**Comment by stefaweb** [comment]
Problem with the regex: first letter after comma deleted

Original:
index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off

Modified:
index_merge=on, ndex_merge_union=on, ndex_merge_sort_union=on, ndex_merge_intersection=on, ndex_merge_sort_intersection=off

**Comment by Skywalker-11** [comment]
this works  preg_replace("/,([^\\s])/", ", $1", $row[$f])

**Comment by stefaweb** [comment]
Ok to push if you agree folk!

**Comment by Skywalker-11** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/420#-:-Kb7AJWpKAu90lSor-GR:bnfp4nl)*

**Comment by Skywalker-11** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/420)*

**Comment by Skywalker-11** [comment]
ready for merge

**Comment by stefaweb** [comment]
yes

**Comment by Skywalker-11** [comment]
this will only apply the line breaks for the single table
https://github.com/Skywalker-11/1.2.0/commit/4d080f744a33c7934fbdfaf8bc4f1276718e5619

**Comment by stefaweb** [comment]
I can delete this PR if you want to handle it?

**Comment by Skywalker-11** [comment]
made a pr to include that changes on your branch

**Comment by stefaweb** [comment]
Reviewed 2 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/420)*

**Comment by Skywalker-11** [comment]
*[mailscanner/functions.php, line 2366 at r6](https://reviewable.io:443/reviews/mailwatch/1.2.0/420#-KbLencNE7PuT9Jy1por:-KbLencNE7PuT9Jy1pos:bpiprrd) ([raw file](https://github.com/mailwatch/1.2.0/blob/ebcca8b0727a1cf7a1c777568918ce6dbe98d928/mailscanner/functions.php#L2366)):*
> ```PHP
>             echo ' <tr>' . "\n";
>             for ($f = 0; $f < $fields; $f++) {
>                 echo '  <td style="background-color: ' . $bgcolor . '; ">' . $row[$f] . '</td>' . "\n";
> ```

this does not seem to work here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/420)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/functions.php, line 2366 at r6](https://reviewable.io:443/reviews/mailwatch/1.2.0/420#-KbLencNE7PuT9Jy1por:-KbLfpYKCt6chzoeNtor:b-4k3f3u) ([raw file](https://github.com/mailwatch/1.2.0/blob/ebcca8b0727a1cf7a1c777568918ce6dbe98d928/mailscanner/functions.php#L2366)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

this does not seem to work here
</blockquote></details>

I've not modified this line?
I have the two shades of gray printed on screen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/420)*

**Comment by Skywalker-11** [comment]
You reverted that preg_replace with your commit https://github.com/mailwatch/1.2.0/pull/420/commits/ebcca8b0727a1cf7a1c777568918ce6dbe98d928. Now it isn't working anymore

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mailscanner/functions.php, line 2366 at r6](https://reviewable.io:443/reviews/mailwatch/1.2.0/420#-KbLencNE7PuT9Jy1por:-KbMbVOuEnxsn7Pf8KMX:b-njs0b3) ([raw file](https://github.com/mailwatch/1.2.0/blob/ff656475696c38bc8d2f24961a277450013d6568/mailscanner/functions.php#L2366)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

I've not modified this line?
I have the two shades of gray printed on screen.

</blockquote></details>

merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/420)*

**Comment by stefaweb** [comment]
Reviewed 1 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/420)*

**Comment by Skywalker-11** [comment]
I don't realy know what you are doing here. Is is on purpose that the preg_replace still isn't in the code again?

**Comment by stefaweb** [comment]
Lost in git...

Seems ok now.

**Comment by Skywalker-11** [comment]
nope. still no preg_replace in the code: https://github.com/mailwatch/1.2.0/blob/ff656475696c38bc8d2f24961a277450013d6568/mailscanner/functions.php#L2366

**Comment by Skywalker-11** [comment]
shall I create a new pr?

**Comment by stefaweb** [comment]
yes go, I delete this one.
I'm tide and do mistake on mistake.

**Pull request closed without merging**
