### PR TITLE
redirect if login page session expired - fixes #1107

### LINKED ISSUE #1107: The return of the infamous dietoken99
As the title said. ;)

Just got it after a session timeout.

dietoken99
Error: unable to validate security token

capture d ecran 2018-09-27 a 15 40 36

EDIT:

I was on rep_message_listing.php.

### PR DESCRIPTION
**Pull request by Skywalker-11**
Fix for #1107
If the session on the login page expires (->invalid token) don't show token error but redirect to login page and ask user to login again

### CODE REVIEW

**Comment by stefaweb** [comment]
Can I close this issue?

**Comment by stefaweb** [comment]
Oops sorry. Already done.

May be it's time to publish 1.2.11 ? ;-)

**Comment by dajones70** [comment]
I am running the latest master 1.2.13 and this problem still exists year later.  Anything I can do to help resolve or test this?

**Comment by ghost** [comment]
Hi @dajones70 

You are still seeing the token error on the login page? 

Does the login page ever expire as expected with this PR, or does it just sit on that screen indefinitely and then throw a token error?

**Comment by xpufx** [comment]
I am not sure if this is related but i am running the current latest version and the session timeout setting has no effect. I am having to log in again almost every time I look at the page and it's making me log in twice before it will let me in. 

I am not seeing a token message though.

**Pull request merged**
