### PR TITLE
Fix for #336 - wrong language translation specified

### LINKED ISSUE #336: Quarantine report missing language translation
Quarantine report is missing "Action" language translations

### PR DESCRIPTION
**Pull request by asuweb**
Fixes #336

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/337)

### CODE REVIEW

**Comment by endelwar** [comment]
Please check this PR against develop branch, it contains quite a few difference, and can't be automatically merged

**Comment by asuweb** [comment]
@endelwar - I noticed a lot of code changes on the develop branch, so I'll check this PR against that branch for future integration and submit a PR for the develop branch.

This PR fixes the bug in the stable (Master branch).

**Comment by stefaweb** [comment]
I'm doing this cleanly. Will post all localisation later today.

**Comment by stefaweb** [comment]
Done in #339 and #340.
This PR #336 can be deleted.

**Pull request closed without merging**
