### PR TITLE
Update functions.php to hide snapd mount point - fix

### PR DESCRIPTION
**Pull request by slsguerra**
Small typo: snap to snapd

### CODE REVIEW

**Comment by endelwar** [comment]
Can you double check this?
I've just installed an Ubuntu 22.04 and I get different results for snap presence in `/proc/mounts` and `mount` command:

*/proc/mounts*

```shell
root@ubuntu22:~# cat /proc/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=1936576k,nr_inodes=484144,mode=755,inode64 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,noexec,relatime,size=398492k,mode=755,inode64 0 0
/dev/mapper/ubuntu--vg-ubuntu--lv / ext4 rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,inode64 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k,inode64 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=27610 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
none /run/credentials/systemd-sysusers.service ramfs ro,nosuid,nodev,noexec,relatime,mode=700 0 0
/dev/sda2 /boot ext4 rw,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=398488k,nr_inodes=99622,mode=700,uid=1000,gid=1000,inode64 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
/dev/loop0 /snap/snapd/19457 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop1 /snap/core20/1974 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop2 /snap/hugo/16793 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop3 /snap/core18/2785 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop4 /snap/nextcloud/35878 squashfs ro,nodev,relatime,errors=continue 0 0
tmpfs /run/snapd/ns tmpfs rw,nosuid,nodev,noexec,relatime,size=398492k,mode=755,inode64 0 0
nsfs /run/snapd/ns/nextcloud.mnt nsfs rw 0 0
/dev/loop5 /snap/core22/817 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop6 /snap/bare/5 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop7 /snap/gtk-common-themes/1535 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop8 /snap/kstars/131 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop9 /snap/kf5-5-106-qt-5-15-9-core22/23 squashfs ro,nodev,relatime,errors=continue 0 0
nsfs /run/snapd/ns/kstars.mnt nsfs rw 0 0
/dev/loop10 /snap/certbot/3024 squashfs ro,nodev,relatime,errors=continue 0 0
```

*mount command*
```shell
root@ubuntu22:~# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=1936576k,nr_inodes=484144,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=398492k,mode=755,inode64)
/dev/mapper/ubuntu--vg-ubuntu--lv on / type ext4 (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=27610)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/dev/sda2 on /boot type ext4 (rw,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=398488k,nr_inodes=99622,mode=700,uid=1000,gid=1000,inode64)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
/var/lib/snapd/snaps/snapd_19457.snap on /snap/snapd/19457 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_1974.snap on /snap/core20/1974 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/hugo_16793.snap on /snap/hugo/16793 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core18_2785.snap on /snap/core18/2785 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/nextcloud_35878.snap on /snap/nextcloud/35878 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=398492k,mode=755,inode64)
nsfs on /run/snapd/ns/nextcloud.mnt type nsfs (rw)
/var/lib/snapd/snaps/core22_817.snap on /snap/core22/817 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/bare_5.snap on /snap/bare/5 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gtk-common-themes_1535.snap on /snap/gtk-common-themes/1535 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/kstars_131.snap on /snap/kstars/131 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/kf5-5-106-qt-5-15-9-core22_23.snap on /snap/kf5-5-106-qt-5-15-9-core22/23 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
nsfs on /run/snapd/ns/kstars.mnt type nsfs (rw)
/var/lib/snapd/snaps/certbot_3024.snap on /snap/certbot/3024 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
```


I don't use Ubuntu or Snap at all, could it be that different Ubuntu version have different output for these 2 situation?

**Comment by slsguerra** [comment]
On my setup (CentOS7) the mount /var/lib/snapd/snaps appers on mailwatch. After chages they disappear

**Comment by endelwar** [comment]
Could you provide the output of `cat /proc/mounts` and `mount` to find a general rule for regex?

**Comment by slsguerra** [comment]
```
# cat /proc/mounts
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=4075752k,nr_inodes=1018938,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_prio,net_cls 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,seclabel,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/sda1 / xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12622 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,seclabel,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
tmpfs /var/spool/MailScanner/incoming tmpfs rw,seclabel,relatime,size=1048576k 0 0
/dev/loop2 /var/lib/snapd/snap/certbot/3024 squashfs ro,context=system_u:object_r:snappy_snap_t:s0,nodev,relatime 0 0
/dev/loop3 /var/lib/snapd/snap/core20/1950 squashfs ro,context=system_u:object_r:snappy_snap_t:s0,nodev,relatime 0 0
/dev/loop1 /var/lib/snapd/snap/core/15419 squashfs ro,context=system_u:object_r:snappy_snap_t:s0,nodev,relatime 0 0
/dev/loop0 /var/lib/snapd/snap/certbot/2913 squashfs ro,context=system_u:object_r:snappy_snap_t:s0,nodev,relatime 0 0
/dev/sdd1 /var/spool/MailScanner/quarantine xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
/dev/mapper/vg_backup-backup /backup xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
/dev/mapper/vg_zimbra-opt /opt xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,seclabel,nosuid,nodev,relatime,size=817304k,mode=700,uid=1000,gid=1000 0 0
/dev/loop6 /var/lib/snapd/snap/core20/1974 squashfs ro,context=system_u:object_r:snappy_snap_t:s0,nodev,relatime 0 0
/dev/loop5 /var/lib/snapd/snap/core/15511 squashfs ro,context=system_u:object_r:snappy_snap_t:s0,nodev,relatime 0 0
tmpfs /run/user/0 tmpfs rw,seclabel,nosuid,nodev,relatime,size=817304k,mode=700 0 0

# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=4075752k,nr_inodes=1018938,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,cpuacct,cpu)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,net_prio,net_cls)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,cpuset)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,freezer)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,perf_event)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/sda1 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12622)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime,seclabel)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
tmpfs on /var/spool/MailScanner/incoming type tmpfs (rw,relatime,seclabel,size=1048576k)
/var/lib/snapd/snaps/certbot_3024.snap on /var/lib/snapd/snap/certbot/3024 type squashfs (ro,nodev,relatime,context=system_u:object_r:snappy_snap_t:s0)
/var/lib/snapd/snaps/core20_1950.snap on /var/lib/snapd/snap/core20/1950 type squashfs (ro,nodev,relatime,context=system_u:object_r:snappy_snap_t:s0)
/var/lib/snapd/snaps/core_15419.snap on /var/lib/snapd/snap/core/15419 type squashfs (ro,nodev,relatime,context=system_u:object_r:snappy_snap_t:s0)
/var/lib/snapd/snaps/certbot_2913.snap on /var/lib/snapd/snap/certbot/2913 type squashfs (ro,nodev,relatime,context=system_u:object_r:snappy_snap_t:s0)
/dev/sdd1 on /var/spool/MailScanner/quarantine type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg_backup-backup on /backup type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/vg_zimbra-opt on /opt type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=817304k,mode=700,uid=1000,gid=1000)
/var/lib/snapd/snaps/core20_1974.snap on /var/lib/snapd/snap/core20/1974 type squashfs (ro,nodev,relatime,context=system_u:object_r:snappy_snap_t:s0)
/var/lib/snapd/snaps/core_15511.snap on /var/lib/snapd/snap/core/15511 type squashfs (ro,nodev,relatime,context=system_u:object_r:snappy_snap_t:s0)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=817304k,mode=700)
```

**Pull request closed without merging**
