### PR TITLE
Modified lists.php for more details in Audit Log

### PR DESCRIPTION
**Pull request by stefaweb**
And new version 0.3.8 for languages files.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/410)

### CODE REVIEW

**Comment by stefaweb** [comment]
Don't publish for the moment.

**Comment by Skywalker-11** [comment]
is this ready for merge?

**Comment by stefaweb** [comment]
yes

**Comment by shawniverson** [comment]
*Look at Stéphane go go go!*

**Comment by stefaweb** [comment]
Closed as integrated in #418

**Pull request merged**
