### PR TITLE
Password Reset Update

### LINKED ISSUE #592: Some problems with password reset
Screen too small.

capture d ecran 2017-02-24 a 09 06 25

Button too large.
Font in button a little too small.

capture d ecran 2017-02-24 a 09 06 35

Where to go after this screen?
No button, no back.

capture d ecran 2017-02-24 a 09 07 06

### PR DESCRIPTION
**Pull request by asuweb**
Fixes #592

### CODE REVIEW

**Comment by stefaweb** [comment]
For fr.php

```
    'auditlogunf63' => 'Demande de réinitialisation de mot de passe - L\'utilisateur %s n\'existe pas.',
    'auditlogreserreqested63' => 'L\'utilisateur %s a demander de réinitialiser son mot de passe. E-Mail de réinitialisation envoyé.',
    'auditlogresetdenied63' => 'L\'utilisateur %s a refusé la réinitialisation de son mot de passe.',
    'auditlogresetsuccess63' => 'La réinitialisation du mot de passe a réussi pour l\'utilisateur %s.',
    'auditlogidmismatch63' => 'La réinitialisation du mot de passe pour l\'utilisateur %s a échouée. L\'ID de réinitialisation ne correspond pas.',
    'auditlogexpired63' => 'La réinitialisation du mot de passe pour l\'utilisateur %s a échouée. L\'ID de réinitialisation a expiré.',
    'auditloglinkerror63' => 'Erreur sur le lien de réinitialisation de l\'E-Mail.',
```

**Comment by stefaweb** [comment]
For `auditloglinkerror63`, the English version is not clear for me (and may be the French translation is not good).

**Comment by asuweb** [comment]
> For auditloglinkerror63, the English version is not clear for me (and may be the French translation is not good).

Basically means that the link in the reset email didn't work - wrong format, missing details that sort of thing

**Comment by stefaweb** [comment]
I'm right with the French loc of auditloglinkerror63 but was not easy. 😀

Not tested yet.

**Comment by Skywalker-11** [comment]
DE:
'auditlogunf63' => 'Versuch zum Zurücksetzen des Passworts - Benutzer nicht gefunden: %s',
'auditlogreserreqested63' => 'Benutzer %s hat ein Zurücksetzen des Passworts angefordert - E-Mail zum Zurücksetzen wurde gesendet',
'auditlogresetdenied63' => 'Zurücksetzen des Passworts verweigert für Benutzer %s',
'auditlogresetsuccess63' => 'Passwort wurde erfolgreich zurückgesetzt für Benutzer %s',
'auditlogidmismatch63' => 'Zurücksetzen des Passworts für Benutzer %s fehlgeschlagen - Rücksetz-ID stimmt nicht überein',
'auditlogexpired63' => 'Zurücksetzen des Passworts für Benutzer %s fehlgeschlagen - Rücksetz-Link abgelaufen',
'auditloglinkerror63' => 'Fehlerhafter Link in der Rücksetz-Mail',

**Comment by stefaweb** [comment]
For fr.php, new version:

```
    'passwdresetrequest63' => 'Demande de nouveau de mot de passe.',
    'p1email63' => 'Une demande de réinitialisation de mot de passe a été reçu pour %s.<br>Si vous n\'avez pas fait cette demande, contactez votre administrateur système immédiatement.<p>Pour réinitialiser votre mot de passe, cliquez sur le lien ci-dessous.<br>',
    '01emailplaintxt63' => 'Demande de réinitialisation de mot de passe.\nUne demande de réinitialisation de mot de passe a été reçue pour %s.\nSi vous n\'avez pas fait cette demande, contactez votre administrateur système immédiatement.\nPour réinitialiser votre mot de passe, veuillez copier et coller le lien ci-dessous dans votre navigateur :\n',
    '01pwd63' => 'Entrer le mot de passe :',
    '02pwd63' => 'Saisir à nouveau le mot de passe :',
    'pwdresetidmismatch63' => 'Incompatibilité de l\'UID. Quelque chose s\'est mal passé.',
    'resetexpired63' => 'Le lien de réinitialisation a expiré. Veuillez faire une nouvelle demande de changement de mot de passe.',
    'brokenlink63' => 'Le lien de réinitialisation manque des paramètres. Essayez de nouveau ou contactez le support.',
    'auditlogunf63' => 'Demande de réinitialisation de mot de passe. L\'utilisateur %s n\'existe pas.',
    'p1email63' => 'Une demande de réinitialisation de mot de passe a été reçu pour %s.<br>Si vous n\'avez pas fait cette demande, contactez votre administrateur système immédiatement.<p>Pour réinitialiser votre mot de passe, cliquez sur le lien ci-dessous.<br>',
    'emailaddress63' => 'Addresse E-Mail :',
    'requestpwdreset63' => 'Demande de nouveau mot de passe.',
```

In English version many dot at the end of sentences are missing.

I've found this concerning the design.

The button with "Forgotten password?" is too large. Reduce the yellow button. Font size is ok.

capture d ecran 2017-02-25 a 08 32 14

The font size in the button "Login" is not the right standard size (font size too small).

capture d ecran 2017-02-25 a 08 32 56

The font size in the button "Login" is not the right standard size (font size too small).

capture d ecran 2017-02-25 a 08 35 05

**Comment by stefaweb** [comment]
On iPhone, in the mail client.

layout really ugly, text cut inside the button

img_0856

**Comment by stefaweb** [comment]
For this one, the best will be to replace the yellow "Forgotten password?" button by a link. 

74cbe386-fb35-11e6-885b-2ed681989000

**Comment by stefaweb** [comment]
In Audit Log.

IIs it normal for the user field to be empty?

capture d ecran 2017-02-25 a 10 24 28

**Comment by asuweb** [comment]
The user isn't logged in, so therefore audit log can't determine who the user is.  It's not worth re-writing the audit log function entirely just for this.  It's logging the IP and associated email address so I think that is sufficient.

**Comment by stefaweb** [comment]
Don't care of this. This was just to know if it was a bug of not.

Found a grammatical error in this one.

`'auditlogreserreqested63' => 'L\'utilisateur %s a demandé de réinitialiser son mot de passe. E-Mail de réinitialisation envoyé.',
`

**Comment by stefaweb** [comment]
Hello @asuweb!
If you've time, seems this PR have a conflict and some small mods to do.

**Comment by stefaweb** [comment]
Hello @asuweb!

For the login screen, the best will be to replace the yellow "Forgotten password?" button by a href link. Having two buttons on the screen does not make the thing very easy to understand. The reset button is too bright.

Just remove the `<button>` tag.

capture d ecran 2017-03-01 a 09 48 21

**Pull request merged**
