### PR TITLE
sf_version.php

### PR DESCRIPTION
**Pull request by stefaweb**
Add a blank line.

### CODE REVIEW

**Comment by stefaweb** [comment]
Upload of then day.
\ not parsed in fr.php

**Comment by stefaweb** [comment]
Bug in fr.php fixed. A comma was missing.

**Comment by endelwar** [comment]
@stefaweb you should separate all this new features on different branch and Pull Request, so that I can merge the single feature after the needed tests and revisions

**Comment by stefaweb** [comment]
Hello!

You talk of translation or of the others changes? Currently, only languages/fr.php is added on my fork. All others changes have been done on the regular files from the master project (not the ones modified for translation).

But, if you explain me how to do, I can do as well.

**Comment by endelwar** [comment]
if you look at "file changed" on top of the page you will see that all you commits are in this PR.
you should create a different branch (`git checkout -b add-french-translation` or `git checkout -b update-upgrade-doc`, etc...), work on a single feature in this new branch and push the branch to your fork, then create a new pull request for each feature or fix.
Also remember to sync the master branch of your fork with current master branch of MailWatch, so that you work on updated code (see problem #186) using this command: `git fetch upstream && git reset --hard upstream/master && git push`; more on this in doc website at http://docs.mailwatch.org/dev/contributing.html

**Comment by stefaweb** [comment]
Close this one with errors.

**Pull request closed without merging**
