### PR TITLE
Fixes #344 - upgrade.php now works with mysqli

### LINKED ISSUE #344: upgrade RC4 issue
While upgrading from 1.2.0. to 1.2.0-rc.4 I discovered some issues in running the upgrade.php. On Fedora 25 (mariadb-10.1.20-1) mysql_connect is not supported anymore. Could you please change them to mysqli functions?

With regards,
Rene

### PR DESCRIPTION
**Pull request by asuweb**
Provides quick fix for #344 

upgrade.php now compatible with mysqli

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/347)

### CODE REVIEW

**Comment by endelwar** [comment]
It would be better using the database class instead of direct mysqli_* functions: one day, not so far I hope, MailWatch will support any php PDO/perl DBD available through database class

**Comment by asuweb** [comment]
I agree, give me half an hour and I'll do it

**Comment by asuweb** [comment]
Tested and working with php 5.6 / centos 6

**Comment by asuweb** [comment]
*[upgrade.php, line 410 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/347#-K_dEn5au9lhfaFNIICp:-K_dEn5au9lhfaFNIICq:b-k6nvyz) ([raw file](https://github.com/mailwatch/1.2.0/blob/6b1f73ce8982839197db170f964bf1886ecbdfd5/upgrade.php#L410)):*
> ```PHP
> } else {
>     echo " FAILED\n";
>     $errors[] = "Database connection failed: " . $link->error;
> ```

needs error handling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/347)*

**Pull request merged**
