### PR TITLE
Fixes #583

### LINKED ISSUE #583: Bug IPSet in detail.php
Select a mail --> detail --> boom

capture d ecran 2017-02-23 a 18 00 13

### PR DESCRIPTION
**Pull request by asuweb**
Fixes #583

### CODE REVIEW

**Comment by stefaweb** [comment]
>  Files changed 223

???

**Comment by asuweb** [comment]
Damn!  Stupid thing!  I'll remove and fix

**Comment by stefaweb** [comment]
I say nothing, because me and Git...

**Comment by Skywalker-11** [comment]
maybe `git rebase upstream/develop` could have helped here

**Comment by asuweb** [comment]
No, I raised the pr against master instead of develop

**Pull request closed without merging**
