### PR TITLE
Translation Updates

### PR DESCRIPTION
**Pull request by rafaelbsd**
I put the new translation variables inside fr.php and nl.php translation files the speed the update process.

### CODE REVIEW

**Comment by stefaweb** [comment]
@rafaelbsd 
I've 38 files waiting to merge... Have a nice merge. ;-)

**Comment by rafaelbsd** [comment]
@stefaweb You too!!!

**Comment by stefaweb** [comment]
@rafaelbsd 

Found:

fdsfdf



Could you please replace the function get_conf_truefalse() in functions.php.

One of my patch have been lost.

This permit a good switch in the other.php page.

[code]
function get_conf_truefalse($name)
{
    if (DISTRIBUTED_SETUP) {
        return true;
    }

    $conf_dir = get_conf_include_folder();
    $MailScanner_conf_file = MS_CONFIG_DIR . 'MailScanner.conf';

    $array_output1 = parse_conf_file($MailScanner_conf_file);
    $array_output2 = parse_conf_dir($conf_dir);

    if (is_array($array_output2)) {
        $array_output = array_merge($array_output1, $array_output2);
    } else {
        $array_output = $array_output1;
    }
    foreach ($array_output as $parameter_name => $parameter_value) {
        $parameter_name = preg_replace('/ */', '', $parameter_name);

        if ((strtolower($parameter_name)) == (strtolower($name))) {
            // Is it a ruleset?
            if (is_readable($parameter_value)) {
                $parameter_value = get_default_ruleset_value($parameter_value);
            }
            $parameter_value = strtolower($parameter_value);
            switch ($parameter_value) {
                case "yes":
                case "1":
                    return true;
                case "no":
                case "0":
                    return false;
                default:
                    // if $parameter_value is a ruleset or a function call return true
                    $parameter_value = trim($parameter_value);
                    if (strlen($parameter_value) > 0) {
                        return true;
                    }

                    return false;
            }
        }
    }

    return false;
}
[/code]

**Comment by stefaweb** [comment]
@rafaelbsd 

Another error.

in quarantine.php: colspan missing line 49.

echo '<tr><th colspan=2>' . __('folder08') . '</th></tr>' . "\n";

**Comment by rafaelbsd** [comment]
Hi, @stefaweb , I´ll change those variables with ":" that you´ve shown. 

Abount functions.php, I didn't undertand: I compare both codes and didn't see difference....

**Comment by stefaweb** [comment]
Just checked online. The functions.php file on git is not the right version for the get_conf_truefalse().

The right version:

case "0":
                return false;
            default:
                // if $parameter_value is a ruleset or a function call return true
                $parameter_value = trim($parameter_value);
                if (strlen($parameter_value) > 0) {
                    return true;
                }

                return false;
        }
    }
}

return false;
}

**Comment by stefaweb** [comment]
@rafaelbsd 

More stuff to solve (based on online master code).

in login.php

Problem with logo. Code not parsed.
If word is absent from loc file, print english word and sentence "not translated)
capture d ecran 2015-06-26 a 08 15 12

In rep_top_mail_relays.php

Enlarge column Country.
Something seems wrong with GeoIP (the IP should resolve)

capture d ecran 2015-06-26 a 08 15 51

**Comment by stefaweb** [comment]
@rafaelbsd 

Syntax error due to translation in user_manager.php

capture d ecran 2015-06-26 a 08 42 47

**Comment by stefaweb** [comment]
@rafaelbsd 

In clamav_status.php

Remove width =100 in <table>.

capture d ecran 2015-06-26 a 08 53 04

**Comment by stefaweb** [comment]
@rafaelbsd 

In detail.php: many " : " to solve.

Y/N in red or green to translate.

capture d ecran 2015-06-26 a 09 04 42

**Comment by stefaweb** [comment]
@rafaelbsd 

In status.php

Client IP not translated.

capture d ecran 2015-06-26 a 09 29 55

**Comment by rafaelbsd** [comment]
Hi, @stefaweb I´ll check those problems now let you know.

**Comment by rafaelbsd** [comment]
Hi, @stefaweb : 

":" Symbols: Some words were not translated in the firts time due to mean the same in all languages, like the word SPAM.
I created those words in loc files to respect the French language (":").

rep_total_mail_relays.php and clamav_status.php: I´m not working in any part of design for now. Just the translations... I hope to start to contribute on that subject soon.

About user_manager.php, I tested all my code here and didn´t found any problem... What action did you do that generated that error?

About Client IP, it was at functions.php. I translated it too.

**Pull request closed without merging**
