### PR TITLE
Feature/filter audit log (#256)

### LINKED ISSUE #256: Filtering Options for Audit Reports
This may be a useful feature for some.

https://forum.efa-project.org/viewtopic.php?f=15&t=1715
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35726923-filtering-options-for-audit-reports?utm_campaign=plugin&utm_content=tracker%2F585686&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F585686&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Skywalker-11**
Fixes #256.
Also removed the old filter part cause it was not useful here cause the available filters are totally different (other table -> other possible filters)

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/426)

### CODE REVIEW

**Comment by stefaweb** [comment]
For fr.php:

```
    'filter33' => 'Filtre',
     'applyfilter33' => 'appliquer',
     'startdate33' => 'Date de départ',
     'enddate33' => 'Date de fin',
```

**Comment by stefaweb** [comment]
Could correct in all languages files:

Added [ ]

```
    'auditlogadded07' => 'Added entry [%s] for %s in the %s',
    'auditlogremoved07' => 'Removed entry [%s] for %s in the %s',
```

This is just cosmetics to be easiest to read.

**Comment by stefaweb** [comment]
Sorry, another one for fr.php:

'mwloginpage01' => 'Page de connexion MailWatch',

**Comment by Skywalker-11** [comment]
ready for merge?

**Pull request merged**
