### PR TITLE
Upgrade VARCHAR list of tables and fields to 191 in upgrade.php

### PR DESCRIPTION
**Pull request by stefaweb**
To check.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/440)

### CODE REVIEW

**Comment by stefaweb** [comment]
```
Testing connectivity to the database ................................. OK
Updating database schema:
 - Convert database to UTF-8.......................................... OK
 - Convert table `audit_log` to UTF-8................................. ALREADY CONVERTED
 - Convert table `autorelease` to UTF-8............................... ALREADY CONVERTED
 - Convert table `blacklist` to UTF-8................................. ALREADY CONVERTED
 - Convert table `inq` to UTF-8....................................... ALREADY CONVERTED
 - Convert table `maillog` to UTF-8................................... ALREADY CONVERTED
 - Convert table `mtalog_ids` to UTF-8................................ ALREADY CONVERTED
 - Convert table `mcp_rules` to UTF-8................................. ALREADY CONVERTED
 - Convert table `mtalog` to UTF-8.................................... ALREADY CONVERTED
 - Convert table `outq` to UTF-8...................................... ALREADY CONVERTED
 - Convert table `sa_rules` to UTF-8.................................. ALREADY CONVERTED
 - Convert table `saved_filters` to UTF-8............................. ALREADY CONVERTED
 - Convert table `spamscores` to UTF-8................................ ALREADY CONVERTED
 - Convert table `user_filters` to UTF-8.............................. ALREADY CONVERTED
 - Convert table `users` to UTF-8..................................... ALREADY CONVERTED
 - Convert table `whitelist` to UTF-8................................. ALREADY CONVERTED
 - Enlarge username field in `users` table............................ OK
 - Enlarge fullname field in `users` table............................ OK
 - Enlarge fullname field in `users` table............................ OK
 - Enlarge username field in `audit_log` table........................ OK
 - Enlarge username field in `autorelease` table...................... OK
 - Enlarge username field in `autorelease` table...................... OK
 - Enlarge username field in `mcp_rules` table........................ OK
 - Enlarge username field in `user_filters` table..................... OK
 - Enlarge user field in `spamscores` table........................... OK
 - Drop `geoip_country` table......................................... OK

Checking MailScanner.conf settings:
 - QuarantineWholeMessage ............................................ OK
 - QuarantineWholeMessagesAsQueueFiles ............................... OK
 - DetailedSpamReport ................................................ OK
 - IncludeScoresInSpamAssassinReport ................................. OK
 - SpamActions ....................................................... OK
 - HighScoringSpamActions ............................................ WARNING
 - AlwaysLookedUpLast ................................................ OK

*** ERROR/WARNING SUMMARY ***
MailScanner.conf: HighScoringSpamActions != store (=delete)
```

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/440)*

**Comment by Skywalker-11** [comment]
*[upgrade.php, line 170 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLhsKa-_wMUpWsIYqU:-KbLhsKa-_wMUpWsIYqV:b-rsxywt) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L170)):*
> ```PHP
>                     '` CONVERT TO CHARACTER SET ' . $mysql_utf8_variant[$server_utf8_variant]['charset'] .
>                     ' COLLATE ' . $mysql_utf8_variant[$server_utf8_variant]['collation'];
>                 executeQuery($sql);
> ```

here is the place where it breaks 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/440)*

**Comment by Skywalker-11** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[upgrade.php, line 183 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLkfUAknIQYwvUUh_n:-KbLkfUAknIQYwvUUh_o:b-d5f6r0) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L183)):*
> ```PHP
> 
>     echo pad(' - Enlarge fullname field in `users` table');
>     $sql = "ALTER TABLE `users` CHANGE `fullname` `fullname` VARCHAR( 191 ) CHARACTER SET " . $mysql_utf8_variant[$server_utf8_variant]['charset'] . " COLLATE " . $mysql_utf8_variant[$server_utf8_variant]['collation'] . " NOT NULL DEFAULT ''";
> ```

can stay at 255 chars

---

*[upgrade.php, line 187 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLklUCAkU3ofQ436rV:-KbLklUCAkU3ofQ436rW:b-d5f6r0) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L187)):*
> ```PHP
> 
>     echo pad(' - Enlarge fullname field in `users` table');
>     $sql = "ALTER TABLE `users` CHANGE `password` `password` VARCHAR( 191 ) CHARACTER SET " . $mysql_utf8_variant[$server_utf8_variant]['charset'] . " COLLATE " . $mysql_utf8_variant[$server_utf8_variant]['collation'] . " NOT NULL DEFAULT ''";
> ```

can stay at 255 chars

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/440)*

**Comment by Skywalker-11** [comment]
varchar only needs to be 191 if it is used as primary or foreign key

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-:-KbLlS3i95jGo8kzdhoG:b-bps0fv)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[upgrade.php, line 187 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLklUCAkU3ofQ436rV:-KbLlK1r24OMKbREIINQ:bno0y41) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L187)):*
<details><summary><i>Previously, Skywalker-11 (Michael Pietsch) wrote…</i></summary><blockquote>

can stay at 255 chars
</blockquote></details>

Michael said that VARCHAR is max 191 in utf8mb4_unicode_ci?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/440)*

**Comment by stefaweb** [comment]
ok, I understand.
I need to remove username and password from the list.
And for the others tables, ok?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-:-KbLmwwNYAzt_CQ2qzBA:byk5u2t)*

**Comment by Skywalker-11** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[upgrade.php, line 187 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLklUCAkU3ofQ436rV:-KbLnudZ-92HVG9reqPY:b-qlj9jd) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L187)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

Michael said that VARCHAR is max 191 in utf8mb4_unicode_ci?
</blockquote></details>

if it is used as primary key

---

*[upgrade.php, line 192 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLoaVAi8LJ4hFQ0isg:-KbLoaVAi8LJ4hFQ0ish:bkotevr) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L192)):*
> ```PHP
>     // Table audit_log
>     echo pad(' - Enlarge username field in `audit_log` table');
>     $sql = "ALTER TABLE `audit_log` CHANGE `user` `user` VARCHAR( 191 ) CHARACTER SET " . $mysql_utf8_variant[$server_utf8_variant]['charset'] . " COLLATE " . $mysql_utf8_variant[$server_utf8_variant]['collation'] . " NOT NULL DEFAULT ''";
> ```

can stay at 255

---

*[upgrade.php, line 197 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLoOgb2XVh4kk_khGS:-KbLoOgb2XVh4kk_khGT:bkotevr) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L197)):*
> ```PHP
>     // Table autorelease
>     echo pad(' - Enlarge username field in `autorelease` table');
>     $sql = "ALTER TABLE `autorelease` CHANGE `msg_id` `msg_id` VARCHAR( 191 ) CHARACTER SET " . $mysql_utf8_variant[$server_utf8_variant]['charset'] . " COLLATE " . $mysql_utf8_variant[$server_utf8_variant]['collation'] . " NOT NULL DEFAULT ''";
> ```

can stay at 255

---

*[upgrade.php, line 201 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLpYkCnPJ0DPvKSZKo:-KbLpYkCnPJ0DPvKSZKp:b-ry2qe8) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L201)):*
> ```PHP
> 
>     echo pad(' - Enlarge username field in `autorelease` table');
>     $sql = "ALTER TABLE `autorelease` CHANGE `uid` `uid` VARCHAR( 191 ) CHARACTER SET " . $mysql_utf8_variant[$server_utf8_variant]['charset'] . " COLLATE " . $mysql_utf8_variant[$server_utf8_variant]['collation'] . " NOT NULL DEFAULT ''";
> ```

can stay 255

---

*[upgrade.php, line 206 at r1](https://reviewable.io:443/reviews/mailwatch/1.2.0/440#-KbLokZi5xhgGT9EGLCe:-KbLokZi5xhgGT9EGLCf:bkoterb) ([raw file](https://github.com/mailwatch/1.2.0/blob/6e8f6a626abccf6721ed19878e4315e248734780/upgrade.php#L206)):*
> ```PHP
>     // Tbale mcp_rules
>     echo pad(' - Enlarge username field in `mcp_rules` table');
>     $sql = "ALTER TABLE `mcp_rules` CHANGE `rule_desc` `rule_desc` VARCHAR( 191 ) CHARACTER SET " . $mysql_utf8_variant[$server_utf8_variant]['charset'] . " COLLATE " . $mysql_utf8_variant[$server_utf8_variant]['collation'] . " NOT NULL DEFAULT ''";
> ```

can stay at 200

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/440)*

**Comment by stefaweb** [comment]
Redo from scratch

**Pull request closed without merging**
