### PR TITLE
Fix localization + style in "Load Average" (functions.php)

### PR DESCRIPTION
**Pull request by stefaweb**

### CODE REVIEW

**Comment by stefaweb** [comment]
Ready to merge.

**Comment by stefaweb** [comment]
I tried without success to add a blank vertical line here as in the others box.

sc

Like this:

sc2

If someone find the solution, I take care of it!

**Comment by Skywalker-11** [comment]
try something like this:
`<td align="right" colspan="2" style="padding: 0"><table width="100%" cellpadding="1" cellspacing="1" style="background-color: #ffffff"><tr>`

**Comment by stefaweb** [comment]
Very close! ;)

Got this but some blank lines are too thick.

capture d ecran 2017-02-08 a 11 58 48
 
`echo '    <tr><td>' . __('loadaverage03') . '</td><td align="right" colspan="2" style="padding: 0"><table width="100%" cellpadding="0" cellspacing="1" style="background-color: #ffffff"><tr><td align="right">' . __('1minute03') . '&nbsp;</td><td align="right">' . $la_1m . '</td></tr><tr><td align="right">' . __('5minutes03') . '&nbsp;</td><td align="right">' . $la_5m . '</td></tr><tr><td align="right">' . __('15minutes03') . '&nbsp;</td><td align="right">' . $la_15m . '</td></tr></table></td>' . "\n";
`

**Comment by asuweb** [comment]
We're splitting pixels here (rather than hairs) - for the sake of 1 pixel, I think we can probably live with it?

**Comment by Skywalker-11** [comment]
I think like asuweb. We can do that for 2.0 redesign but should stick with it in 1.2.0

**Comment by stefaweb** [comment]
I wrote "not urgent" and wishlist...
;-)

**Comment by stefaweb** [comment]
Style Ok. I removed the table.

capture d ecran 2017-02-08 a 15 12 15

**Pull request merged**
