### PR TITLE
fixes #424

### LINKED ISSUE #424: Bug in lists.php (Go to message)
If we delete a black or white entry, we got this:

capture d ecran 2017-01-22 a 17 53 26

The number is the entry number ($id) of the deleted entry.

### PR DESCRIPTION
**Pull request by Skywalker-11**
fixes #424 

This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/429)

### CODE REVIEW

**Comment by stefaweb** [comment]
delete no longer works
when we click nothing append

**Comment by stefaweb** [comment]
delete of white list don't work
delete of black list works

**Comment by stefaweb** [comment]
Seem the problem is more complex.
Sometime, the entry is deleted, sometime not.

**Comment by Skywalker-11** [comment]
Works here. if you do a var_dump of `$_GET['listid']` does that contain a valid id for the blacklist/whitelist entry?

**Comment by Skywalker-11** [comment]
There shouldn't be a difference between black/whitelist cause both use the same function to make the link and delete the entries

**Comment by stefaweb** [comment]
Have a look of the screen shot.

I click to delete the entry 881 and after a short "refresh", the entry is still in the list.

capture-d ecran-2017-01-23-a-11 11 45

**Comment by stefaweb** [comment]
Sorry, my lists.php file was not uptodate.
I replaced all the file and now it works.

**Comment by Skywalker-11** [comment]
ready for merge

**Pull request merged**
