### PR TITLE
jpgraph 4.0.2 upgrade and patch for imageantialias()

### PR DESCRIPTION
**Pull request by stefaweb**
My first test using different "branch".

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/389)

### CODE REVIEW

**Comment by stefaweb** [comment]
See #386

**Comment by endelwar** [comment]
Please remove examples direcotiry, they are not required and make the install package bigger

**Comment by endelwar** [comment]
I think that is better to alter line 110 of `gd_image.inc.php` to `return true` instead of `JpGraphError::RaiseL(25128);` when this function is not implemented by linux distributions: a less defined graph is better that a error message.

Also for Debian is better to use dotdeb.org packages, which are more updated and contains the PHP forked GD library that contains this function (and others), Ubuntu people can use ondrej/php PPA

**Comment by stefaweb** [comment]
I'm generally using dotdeb too but I was trying with "standard" Debian stuff first...

For jpgraph patch. Do as you prefer.

When the patch will be ok, I'll try a last time and will switch my server to dotdeb.

**Pull request merged**
