### PR TITLE
Refactoring to reduce code duplication and code smells

### PR DESCRIPTION
**Pull request by Skywalker-11**
This PR consists of two main changes that are merge the relay scripts for postfix and sendmail into one class and using one method for the statistic pages to generate the tables. 

The smaller changes comes mainly from here
[https://insight.sensiolabs.com/projects/2930c654-5978-4556-b2ef-c7eada31ea08/analyses/3](https://insight.sensiolabs.com/projects/2930c654-5978-4556-b2ef-c7eada31ea08/analyses/3)

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/461)

### CODE REVIEW

**Comment by endelwar** [comment]
💯 
This is a fantastic PR!

**Comment by Skywalker-11** [comment]
I hope it is reviewable 😄 
It is probably easier to look through the single commits to see what is changing

**Comment by Skywalker-11** [comment]
Review status: 0 of 21 files reviewed at latest revision, 8 unresolved discussions.

---

*[mailscanner/functions.php, line 1623 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-Kboiuo5G7Fs8_VfiLSY:-Kboiuo5G7Fs8_VfiLSZ:b-a394zd) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/mailscanner/functions.php#L1623)):*
> ```PHP
> 
> /**
>  * @param $sql the sql query for which the page will be created
> ```

the changes from here to the start of function db_table basically moves the code part that creates the html for paging in the table to a seperate method

---

*[mailscanner/functions.php, line 3727 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-Kbojjb0PXDJUy29gRFW:-Kbojjb0PXDJUy29gRFX:b-rmzsvm) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/mailscanner/functions.php#L3727)):*
> ```PHP
> }
> 
> function printGraphTable($filename, $dataColumnTitle, array $data, array $data_names, array $data_size, $scale = 1)
> ```

this function contains the code of the rep_top_*_by_*.php classes that generates the html for tables and graphes. The $scale parameter is not used everywhere so it is default 1

---

*[mailscanner/mtalogprocessor.inc.php, line 2 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-KbokoMITxA-_QrrWAed:-KbokoMJDoof7LPq89Fp:bs46jth) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/mailscanner/mtalogprocessor.inc.php#L2)):*
> ```PHP
> <?php 
> ```

This is a new class that puts the doit() function and parser classes from postfix_relay.php and sendmail_relay.php into a single class. To do this it contains the code that were the same in that files and injects parts that differ through call of the functions getRejectReasons() and getRulesets()

---

*[mailscanner/postfix_relay.php, line 52 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-KbolrtYcZ2sL-iDhv-T:-KbolrtYcZ2sL-iDhv-U:b-v4wlrh) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/mailscanner/postfix_relay.php#L52)):*
> ```PHP
>     }
>     
>     public function getRejectReasons()
> ```

this part differs from sendmail (comes from https://github.com/mailwatch/1.2.0/blob/develop/mailscanner/postfix_relay.php#L219 )

---

*[mailscanner/postfix_relay.php, line 67 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-Kbom796oMOKBCaijrzb:-Kbom796oMOKBCaijrzc:b-dsq1wd) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/mailscanner/postfix_relay.php#L67)):*
> ```PHP
>     }
>     
>     public function extractKeyValuePairs($match)
> ```

from https://github.com/mailwatch/1.2.0/blob/develop/mailscanner/postfix_relay.php#L119

---

*[mailscanner/syslog_parser.inc.php, line 1 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-KbomIK2ytT7MWW5fnC3:-KbomIK2ytT7MWW5fnC4:b-d2nv1d) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/mailscanner/syslog_parser.inc.php#L1)):*
> ```PHP
> <?php 
> ```

moved this class out of postfix_relay.php and sendmail_relay.php to a seperate file

---

*[mailscanner/languages/en.php, line 659 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-KbonSir1XtASSO05XrW:-KbonSir1XtASSO05XrX:brqqki9) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/mailscanner/languages/en.php#L659)):*
> ```PHP
>     'toprecipdomqt40' => 'Top Recipients Domains by Quantity',
>     'top10recipdomqt40' => 'Top 10 Recipients Domains by Volume',
>     'domain40' => 'Domain',
> ```

the following changed translations moved to the functions class so it is now count03 and size03. Same for other languages

---

*[tools/Sendmail_relay/sendmail_relay.php, line 56 at r2](https://reviewable.io:443/reviews/mailwatch/1.2.0/461#-KbongOakYcrU59PW9D4:-KbongOakYcrU59PW9D5:bdac0ue) ([raw file](https://github.com/mailwatch/1.2.0/blob/1049f11327b8a51202354fdc27c7251591dbf9a5/tools/Sendmail_relay/sendmail_relay.php#L56)):*
> ```PHP
>     }
>     
>     public function getRulesets()
> ```

from https://github.com/mailwatch/1.2.0/blob/develop/tools/Sendmail_relay/sendmail_relay.php#L217

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/461)*

**Comment by Skywalker-11** [comment]
Should be ready for merge

**Pull request merged**
