### PR TITLE
fr.php update

### PR DESCRIPTION
**Pull request by stefaweb**
Added missing localized variables.

---
This change is [Reviewable](https://reviewable.io/reviews/mailwatch/1.2.0/274)

### CODE REVIEW

**Comment by endelwar** [comment]
Removed punctuation marks should be added in other existing translation files, where translations are available 

---

Review status: 0 of 14 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[mailscanner/detail.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrnhb9v6DToxpCtPam:-KPrnhbAelBztXNZBZuK:b-acws4v) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/detail.php#L81)):*
> ```PHP
>   CASE WHEN isspam>0 THEN '$yes' ELSE '$no' END AS '" . __('spam04') . "',
>   CASE WHEN ishighspam>0 THEN '$yes' ELSE '$no' END AS '" . __('hscospam04') . "',
>   CASE WHEN issaspam>0 THEN '$yes' ELSE '$no' END AS '" . __('assassinspam04') . "',
> ```

why is this not called "spamassassinspam04" ?

---

*[mailscanner/functions.php, line 339 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KProqwMoKfVKyujzFYB:-KProqwNlF7vP0PFFKRL:bf0fkgc) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/functions.php#L339)):*
> ```PHP
>             echo '    <tr><td>' . ucwords(
>                     $mta
>                 ) . __('comma03') . '</td><td align="center">' . $running . '</td><td align="right">' . $procs . '</td></tr>' . "\n";
> ```

This should be called "colon03"

---

*[mailscanner/geoip_update.php, line 201 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrpnib71JUMbJiNPUr:-KPrpnicjngFwzKmLKFH:bo2z5bd) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/geoip_update.php#L201)):*
> ```PHP
>         } else {
>             // unable to read or write to the directory
>             die(__('norread15') . " " . $extract_dir . " directory.\n");
> ```

also "directory" should be translate

---

*[mailscanner/login.php, line 56 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrqLsAMtmqZNFgFzDD:-KPrqLsBL2e3l4engo8p:b-jvy5w9) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/login.php#L56)):*
> ```PHP
>         .login {
>             margin: 50px auto;
>             width: 350px;
> ```

Did you tested this change with all languages?

---

*[mailscanner/rep_sa_rule_hits.php, line 134 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrqiMxST71xUL2RvT1:-KPrqiMxST71xUL2RvT2:b-qy3kpb) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/rep_sa_rule_hits.php#L134)):*
> ```PHP
> <TR BGCOLOR=\"#EBEBEB\">
>  <TD>$key</TD>
>  <TD>" . htmlentities(return_sa_rule_desc(strtoupper($key))) . "</TD>
> ```

return_sa_rule_desc already include htmlentities() (in develop branch)

---

*[mailscanner/sf_version.php, line 63 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrBnTt7LlM5TvzCQp:-KPrrBnTt7LlM5TvzCQq:b-4d5wio) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L63)):*
> ```PHP
> 
>     echo '<br>' . "\n";
>     echo 'MailWatch ' . __('version11') . " ". $mailwatch_version . '<br>' . "\n";
> ```

just add a space in fr.php translation file, and on other language files if needed (I don't know (my bad) any other languages that need a space before and after punctuation marks)

---

*[mailscanner/sf_version.php, line 65 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrGT2phqeLG710Cyr:-KPrrGT2phqeLG710Cys:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L65)):*
> ```PHP
>     echo 'MailWatch ' . __('version11') . " ". $mailwatch_version . '<br>' . "\n";
>     echo '<br>' . "\n";
>     echo 'MailScanner ' . __('version11') . " ". $mailscanner_version . '<br>' . "\n";
> ```

just add a space in translation file

---

*[mailscanner/sf_version.php, line 70 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrHR62u8wseEE3OeH:-KPrrHR62u8wseEE3OeI:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L70)):*
> ```PHP
>     // Add test for others virus scanners.
>     if (preg_match('/clam/i', $virusScanner)) {
>         echo 'ClamAV ' . __('version11') . " ";
> ```

just add a space in translation file

---

*[mailscanner/sf_version.php, line 75 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrI0XOeYY0uZM-zOg:-KPrrI0XOeYY0uZM-zOh:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L75)):*
> ```PHP
>     }
>     echo '<br>' . "\n";
>     echo 'SpamAssassin ' . __('version11') . " ";
> ```

just add a space in translation file

---

*[mailscanner/sf_version.php, line 79 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrIs8VGyIMXwwLkvJ:-KPrrIs8VGyIMXwwLkvK:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L79)):*
> ```PHP
>     echo '<br>' . "\n";
>     echo '<br>' . "\n";
>     echo 'PHP ' . __('version11') . " " . $php_version . '<br>' . "\n";
> ```

just add a space in translation file

---

*[mailscanner/sf_version.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrJKPmJ8I0TZ8_KI0:-KPrrJKPmJ8I0TZ8_KI1:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L81)):*
> ```PHP
>     echo 'PHP ' . __('version11') . " " . $php_version . '<br>' . "\n";
>     echo '<br>' . "\n";
>     echo 'MySQL ' . __('version11') . " " . $mysql_version . '<br>' . "\n";
> ```

just add a space in translation file

---

*[mailscanner/sf_version.php, line 83 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrhQ8PRH7SuwGpu8-:-KPrrhQ8PRH7SuwGpu80:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L83)):*
> ```PHP
>     echo 'MySQL ' . __('version11') . " " . $mysql_version . '<br>' . "\n";
>     echo '<br>' . "\n";
>     echo 'GeoIP Database ' . __('version11') . " ";
> ```

just add a space in translation file

---

*[mailscanner/sf_version.php, line 87 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrhn0PLE8wYQvmsJW:-KPrrhn0PLE8wYQvmsJX:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L87)):*
> ```PHP
>         echo $geoipv4_version;
>     } else {
>         echo __('nodbdown11') ." ";
> ```

just add a space in translation file

---

*[mailscanner/sf_version.php, line 90 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrriMCfNsWDnAtTwX0:-KPrriMCfNsWDnAtTwX1:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L90)):*
> ```PHP
>     }
>     echo "<br>\n<br>\n";
>     echo 'GeoIPv6 Database ' . __('version11') ." ";
> ```

just add a space in translation file

---

*[mailscanner/user_manager.php, line 49 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrtyIv0CKLkUpQaCU:-KPrrtyIv0CKLkUpQaCV:bpakbq7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/user_manager.php#L49)):*
> ```PHP
>

**Comment by stefaweb** [comment]
Space:

Space in code are ok for any language. They are to separate sentence or variable.

Space for comma or other punctuation characters are in language files.

**Comment by endelwar** [comment]
You're right, didn't see #273

**Comment by stefaweb** [comment]
spamassassinspam04 better

How to manage all these comments?

**Comment by stefaweb** [comment]
Review status: 0 of 14 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[mailscanner/detail.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrvL5qmfFeHN_GohO6:-KPrvL5rgHDne1pfmT0n:bc4sjc3) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/detail.php#L81)):*
> spamassassinspam04

better with spamassassinspam04...

---

*[mailscanner/functions.php, line 339 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KProqwMoKfVKyujzFYB:-KPrwMYpQKJo3XbYJuE6:blmeju9) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/functions.php#L339)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> This should be called "colon03"
</details>
look language file. comma03 is to manage "xxx :" and xxx:".
(with and without space)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by endelwar** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[mailscanner/functions.php, line 339 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KProqwMoKfVKyujzFYB:-KPrxdxFrOcX876oX4b0:b-190zu7) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/functions.php#L339)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> look language file. comma03 is to manage "xxx :" and xxx:".
> (with and without space)
</details>
I agree and use it where needed, but ":" is called colon while "," is comma :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
big mistake !

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[mailscanner/detail.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrvL5qmfFeHN_GohO6:-KPs-Y85XlMxhzJp7JYq:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/detail.php#L81)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> > spamassassinspam04
> 
> better with spamassassinspam04...
> 
</details>
Done.

---

*[mailscanner/functions.php, line 339 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KProqwMoKfVKyujzFYB:-KPs0VL45RzdnjFnkrr9:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/functions.php#L339)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> I agree and use it where needed, but ":" is called colon while "," is comma :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[mailscanner/login.php, line 56 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrqLsAMtmqZNFgFzDD:-KPs0ruBhdy4poZDNUwl:b2rbukg) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/login.php#L56)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> Did you tested this change with all languages?
</details>
only french and english. Should have space for german.

---

*[mailscanner/sf_version.php, line 63 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrBnTt7LlM5TvzCQp:-KPs1GewhR8u2_W7pWpC:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L63)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in fr.php translation file, and on other language files if needed (I don't know (my bad) any other languages that need a space before and after punctuation marks)
</details>
Done.

---

*[mailscanner/sf_version.php, line 65 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrGT2phqeLG710Cyr:-KPs1ILxBVcZYjmPKFzw:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L65)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/sf_version.php, line 70 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrHR62u8wseEE3OeH:-KPs1IrFfMBFRw86ZaZS:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L70)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/sf_version.php, line 75 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrI0XOeYY0uZM-zOg:-KPs1KDxsSuD8XB3kziV:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L75)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/sf_version.php, line 79 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrIs8VGyIMXwwLkvJ:-KPs1Kn_uNMyxauuefoq:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L79)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/sf_version.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrJKPmJ8I0TZ8_KI0:-KPs1LZZr4kENOg3n-A7:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L81)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/sf_version.php, line 83 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrhQ8PRH7SuwGpu8-:-KPs1MNRpmCEdB_eBmpE:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L83)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/sf_version.php, line 87 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrhn0PLE8wYQvmsJW:-KPs1NDWn-Ot9BucXeeB:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L87)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/sf_version.php, line 90 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrriMCfNsWDnAtTwX0:-KPs1ODuAlTE9kWk4o0D:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/sf_version.php#L90)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/user_manager.php, line 49 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrrtyIv0CKLkUpQaCU:-KPs1PCcmvgn5Xtbn3Ww:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/user_manager.php#L49)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> just add a space in translation file
</details>
Done.

---

*[mailscanner/user_manager.php, line 194 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrsHAfTjE3fwO1EOCw:-KPs1QhNuiNw5VD8xSuU:bbdeba8) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/user_manager.php#L194)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> the last one should be "scaneforspam12"
</details>
Should check. Confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by endelwar** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mailscanner/geoip_update.php, line 201 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrpnib71JUMbJiNPUr:-KPs3mLlWawIfWOxGyXe:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/geoip_update.php#L201)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> also "directory" should be translate
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mailscanner/geoip_update.php, line 201 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPs4pqD4M6bVFNOQ0Mx:-KPs3jD8LCjlkUtJMC16:b-fnw0g1) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/geoip_update.php#L201)):*
> 'norread15

---

*[mailscanner/rep_sa_rule_hits.php, line 134 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrqiMxST71xUL2RvT1:-KPs6HG17YwIPOdtENds:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/rep_sa_rule_hits.php#L134)):*
<details><summary><i>Previously, endelwar (Manuel Dalla Lana) wrote…</i></summary>
> return_sa_rule_desc already include htmlentities() (in develop branch)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mailscanner/detail.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrvL5qmfFeHN_GohO6:-KPs78gJpuFfw7cuQrxH:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/detail.php#L81)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> Done.
</details>
Done.

---

*[mailscanner/geoip_update.php, line 201 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPs4pqD4M6bVFNOQ0Mx:-KPs7Abjvd5dyNO9ccjw:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/geoip_update.php#L201)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> > 'norread15
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mailscanner/detail.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrvL5qmfFeHN_GohO6:-KPs9kIjQfSL67xX76xm:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/detail.php#L81)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> Done.
</details>
Done.

---

*[mailscanner/geoip_update.php, line 201 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPs4pqD4M6bVFNOQ0Mx:-KPs9mlrHKxmrYzJ4yy8:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/geoip_update.php#L201)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
continuous-integration/styleci/pr — The StyleCI analysis has failed - 1 file needs addressing

Blocked. Don't understand why.

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mailscanner/detail.php, line 81 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrvL5qmfFeHN_GohO6:-KPsB2g6pcjTDcaXI2q7:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/detail.php#L81)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> Done.
</details>
Done.

---

*[mailscanner/rep_sa_rule_hits.php, line 134 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrqiMxST71xUL2RvT1:-KPsB8LDsJFLq8_aArJx:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/rep_sa_rule_hits.php#L134)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mailscanner/user_manager.php, line 194 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrsHAfTjE3fwO1EOCw:-KPsC2292hmy9rnF4oIr:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/user_manager.php#L194)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary>
> Should check. Confusing.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
Review status: 11 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mailscanner/user_manager.php, line 194 \[r1\]](https://reviewable.io:443/reviews/mailwatch/1.2.0/274#-KPrsHAfTjE3fwO1EOCw:-KPsD7O6KZmpBCPTOYV2:bqiq8hm) ([raw file](https://github.com/mailwatch/1.2.0/blob/9053f68ca196726c34223e717b98b0ac1c08dbaa/mailscanner/user_manager.php#L194)):*
> scaneforspam12

replaced with scanforspam212

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/274)*

**Comment by stefaweb** [comment]
I prefer to close this one. I'm again lost with github.

**Pull request closed without merging**
