### PR TITLE
Fixes for Mailwatch.pm, SQLBlackWhiteList.pm and SQLSpamSettings.pm for utf8mb4

### PR DESCRIPTION
**Pull request by stefaweb**
Done.

- Added support for utf8 or utf8mb4 depending of database version
- New location for dbitrace.log as MailScanner do not have the right to write in /root.
- Added version in Mailwatch.pm.
- Updated version in SQLBlackWhiteList.pm and SQLSpamSettings.pm.
- Updated disclaimer.
- Updated log messages.
- Removed #$dbh->commit; no longer used
- Works without changes in /etc/mysql/my.cnf (#430).

References: #428, #430, #345

### CODE REVIEW

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Others perl scripts for MailScanner have this:

```
use vars qw($VERSION);

### The package version, both in 1.23 style *and* usable by MakeMaker:
$VERSION = substr q$Revision: 1.4 $, 10;
```

Do we need to add these lines and correct version?

**Comment by stefaweb** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Don't use for the moment.
The mods in MailWatch.pm seems to works but after encoding is not good in screen on MailWatch GUI.

**Comment by stefaweb** [comment]
Works !!!!!

capture d ecran 2017-01-30 a 11 51 32

The one with V-DAY is sent as this:
`=?utf-8?Q?=F0=9F=92=98=C2=A0Single=20or=20Taken=2C=20we=27re=20got=20you=20covered=20this=20V=2DDAY?=`

**Comment by stefaweb** [comment]
Works without changes in my.cnf.

**Comment by stefaweb** [comment]
SQLBlackWhiteList.pm and SQLSpamSettings.pm not working yet.

**Comment by stefaweb** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[MailScanner_perl_scripts/SQLBlackWhiteList.pm, line 141 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/425#-KbjtVjCLYcNGUGRFuqr:-KbjtVjCLYcNGUGRFuqs:b-4b18i9) ([raw file](https://github.com/mailwatch/1.2.0/blob/2d746cabc46e8bd7b5b89d54bb17d7426b387a9f/MailScanner_perl_scripts/SQLBlackWhiteList.pm#L141)):*
> { PrintError => 0, AutoCommit => 1, RaiseError => 1, mysql_enable_utf8 => 1 }

Was AutoCommit => 0

AutoCommit => 1 or AutoCommit => 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[MailScanner_perl_scripts/SQLSpamSettings.pm, line 152 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/425#-Kbju-CXnFzMspw0-VGx:-Kbju-CXnFzMspw0-VGy:b-4b18i9) ([raw file](https://github.com/mailwatch/1.2.0/blob/2d746cabc46e8bd7b5b89d54bb17d7426b387a9f/MailScanner_perl_scripts/SQLSpamSettings.pm#L152)):*
> { PrintError => 0, AutoCommit => 1, RaiseError => 1, mysql_enable_utf8 => 1 }

Was AutoCommit => 0

AutoCommit => 1 or AutoCommit => 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[MailScanner_perl_scripts/SQLBlackWhiteList.pm, line 141 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/425#-KbjtVjCLYcNGUGRFuqr:-KbjuRBJdHMPUBqv2lfj:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/2d746cabc46e8bd7b5b89d54bb17d7426b387a9f/MailScanner_perl_scripts/SQLBlackWhiteList.pm#L141)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

> { PrintError => 0, AutoCommit => 1, RaiseError => 1, mysql_enable_utf8 => 1 }

Was AutoCommit => 0

AutoCommit => 1 or AutoCommit => 0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[MailScanner_perl_scripts/SQLSpamSettings.pm, line 152 at r8](https://reviewable.io:443/reviews/mailwatch/1.2.0/425#-Kbju-CXnFzMspw0-VGx:-KbjuThHAbQQzEd9kAfj:b-896fix) ([raw file](https://github.com/mailwatch/1.2.0/blob/2d746cabc46e8bd7b5b89d54bb17d7426b387a9f/MailScanner_perl_scripts/SQLSpamSettings.pm#L152)):*
<details><summary><i>Previously, stefaweb (Stéphane) wrote…</i></summary><blockquote>

> { PrintError => 0, AutoCommit => 1, RaiseError => 1, mysql_enable_utf8 => 1 }

Was AutoCommit => 0

AutoCommit => 1 or AutoCommit => 0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mailwatch/1.2.0/425)*

**Comment by stefaweb** [comment]
I still have:

`Jan 30 19:31:46 antispam-dev mysqld: 170130 19:31:46 [Warning] Aborted connection 2519 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)`

And if we use `$dbh->ping();` ?

**Comment by Skywalker-11** [comment]
Maybe it is also possible to restart the connection after a given time to circumvent that problem

**Comment by asuweb** [comment]
@stefaweb - I'm not seeing any of those messages on the Debian dev server that I'm running

**Comment by stefaweb** [comment]
For reference:

`WARNING: DBD::mysql prior to version 4.042 had different and buggy behaviour when the attribute mysql_enable_utf8 was enabled! Input statement and bind parameters were never encoded to UTF-8 octets and retrieved columns were always UTF-8 decoded regardless of the column charset (except binary charsets).`

I added SET NAME to the perl code to ovoid this problem with previous version of DBD::mysql.

**Comment by stefaweb** [comment]
@asuweb: see #345

**Comment by stefaweb** [comment]
No more message with PrintError => 1

```
Jan 31 06:35:35 antispam-dev mysqld: 170131  6:35:35 [Warning] Aborted connection 4123 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jan 31 08:04:51 antispam-dev mysqld: 170131  8:04:51 [Warning] Aborted connection 4374 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jan 31 08:20:18 antispam-dev mysqld: 170131  8:20:18 [Warning] Aborted connection 4439 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jan 31 09:13:28 antispam-dev mysqld: 170131  9:13:28 [Warning] Aborted connection 4596 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jan 31 09:36:59 antispam-dev mysqld: 170131  9:36:59 [Warning] Aborted connection 4659 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
```

**Comment by stefaweb** [comment]
Not sure that the persistent connection is really working in MailWatch.pm.

After a mailscanner restart:

```
MariaDB [(none)]> show processlist;
+------+-----------+-----------+-------------+---------+------+-------+------------------+----------+
| Id   | User      | Host      | db          | Command | Time | State | Info             | Progress |
+------+-----------+-----------+-------------+---------+------+-------+------------------+----------+
| 5094 | mailwatch | localhost | mailscanner | Sleep   |    8 |       | NULL             |    0.000 |
| 5120 | root      | localhost | NULL        | Query   |    0 | init  | show processlist |    0.000 |
+------+-----------+-----------+-------------+---------+------+-------+------------------+----------+
2 rows in set (0.00 sec)

```

After the timeout:

```
MariaDB [(none)]> show processlist;
+------+------+-----------+------+---------+------+-------+------------------+----------+
| Id   | User | Host      | db   | Command | Time | State | Info             | Progress |
+------+------+-----------+------+---------+------+-------+------------------+----------+
| 5082 | root | localhost | NULL | Query   |    0 | init  | show processlist |    0.000 |
+------+------+-----------+------+---------+------+-------+------------------+----------+
1 row in set (0.00 sec)

```

**Comment by stefaweb** [comment]
I added "mysql_auto_reconnect => 1" to try. 

NO change. I still have the disconnect problem in log and the connection don't go up after disconnect.

`{ PrintError => 0, AutoCommit => 1, RaiseError => 1, mysql_auto_reconnect => 1, mysql_enable_utf8mb4 => 1 }`

**Comment by stefaweb** [comment]
Found something in MailWatch.pm.

Line 178:

```
        # Check to make sure DB connection is still valid
        InitConnection unless $dbh->ping;
```

But in the DBD::mysql doc, the wrote:   $dbh->ping();

I changed it in MailWatch.pm. No error but I still have the "Aborted connection" message.

**Comment by stefaweb** [comment]
Found two errors string in dbitrace.log:

```
    -> STORE for DBD::mysql::db (DBI::db=HASH(0x3c82a58)~INNER 'mysql_enable_utf8mb4' 1) thr#1551010
$h->{'mysql_enable_utf8mb4'}=1 ignored for invalid driver-specific attribute
```

```
    -> disconnect_all for DBD::mysql::dr (DBI::dr=HASH(0x3e0a438)~0x3c95738) thr#1551010
    <- disconnect_all= ( ) [0 items] (not implemented) at DBI.pm line 750
```

If someone know what these errors means?

**Comment by endelwar** [comment]
> If someone know what these errors means?

Upgrade your DBD::mysql driver: utf8mb4 support was added in version 4.032, Debian 8 ships with 4.028

**Comment by stefaweb** [comment]
Hello,

All is fine with stock debian package version and the new MailWatch.pm except the "Aborted connection" message (I had it before #345). I well receive, store, send and print on gui, utf8bm4 messages. Seems "cosmetic".

I can't upgrade to last DBD::mysql 4.041. Not available as .deb for Jessie.
If I try to install the cpan version, I broke dependencies for mysql, mariadb and fuzzyocr.
Jessie package is dependent of perl >= 5.24.1.

Not found a backport or I should build it from source.

This `$h->{'mysql_enable_utf8mb4'}=1 ignored for invalid driver-specific attribute` seems related to: 

`{ PrintError => 0, AutoCommit => 1, RaiseError => 1, mysql_auto_reconnect => 1, mysql_enable_utf8mb4 => 1 }`

But I "force" utf8mb4 with `$dbh->do('SET NAMES utf8mb4');` to ovoid this problem.


https://github.com/perl5-dbi/DBD-mysql

```
2016-12-12 Patrick Galbraith, Michiel Beijen, DBI/DBD community (4.041_1)
* Unicode fixes: when using mysql_enable_utf8 or mysql_enable_utf8mb4,
  previous versions of DBD::mysql did not properly encode input statements
  to UTF-8 and retrieved columns were always UTF-8 decoded regardless of the
  column charset.
  Fix by Pali Rohár.
  Reported and feedback on fix by Marc Lehmann
  (https://rt.cpan.org/Public/Bug/Display.html?id=87428)
  Also, the UTF-8 flag was not set for decoded data:
  (https://rt.cpan.org/Public/Bug/Display.html?id=53130)
```

**Comment by stefaweb** [comment]
Ready to publish as "Aborted connection" message seems "cosmetic" and @asuweb don't have it on his own dev server.

@asuweb : Are-you using mysql or mariaDB?

**Comment by asuweb** [comment]
@stefaweb -

```
 mysql -V
mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by stefaweb** [comment]
@asuweb: I've exactly the same version.

Found this to check:

In MailWatch.pm: 

`     $sth = $dbh->prepare("INSERT INTO maillog (timestamp, id, size, from_address, from_domain, to_address, to_domain, subject, clientip, archive, isspam, ishighspam, issaspam, isrblspam, spamwhitelisted, spamblacklisted, sascore, spamreport, virusinfected, nameinfected, otherinfected, report, ismcp, ishighmcp, issamcp, mcpwhitelisted, mcpblacklisted, mcpsascore, mcpreport, hostname, date, time, headers, quarantined) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)") or`

Need to check if the insert and others parts of the MailWatch.pm code is accurate with new database schema.

The INSERT in the curent MailWatch.pm have 34 columns and the uptodate database 37 columns.

Same check to do for SQLBlackWhiteList.pm and SQLSpamSettings.pm.

**Comment by Skywalker-11** [comment]
what are isfp and isfn used for?

**Comment by asuweb** [comment]
@Skywalker-11 - 

`isfp` - false positive
`isfn` - false negative.

used in `function quarantine_learn`

**Comment by asuweb** [comment]
@stefaweb 

>  missing: maillog_id   but AUTO_INCREMENT
            missing: isfp
            missing: isfn

They're implemented elsewhere and don't involve mailwatch.pm

**Comment by stefaweb** [comment]
ok, great.

I'd a look on the two others files. Nothing found something special.

**Comment by stefaweb** [comment]
I'me still try to find where come from the "Aborted connection".

In MailWatch.pm, we have a routine to close the connexion. Are-we sure that in ALL CASE, the connexion is well closed?

```
sub ExitLogging {
    # Server exit - commit changes, close socket, and exit gracefully.
    close(SERVER);
    #$dbh->commit or die $dbh->errstr;
    $dbh->disconnect;
    exit;
}
```

**Comment by stefaweb** [comment]
I switched on log in mysql.

I dont see "Quit" for the "aborted" process.

`[Warning] Aborted connection 1383 to db: 'mailscanner' user: 'mwmailscanner' host: 'localhost' (Got timeout reading communication packets)`

In mysql.log:

```
1383 Connect   mailwatch@localhost as anonymous on mailscanner

1383 Query     SET NAMES utf8mb4

1383 Query     INSERT INTO maillog (timestamp, id, size, from_address, from_domain, to_address, to_domain, subject, clientip, archive, isspam, ishighspam, issaspam, isrblspam, spamwhitelisted, spamblacklisted, sascore, spamreport, virusinfected, nameinfected, otherinfected, report, ismcp, ishighmcp, issamcp, mcpwhitelisted, mcpblacklisted, mcpsascore, mcpreport, hostname, date, time, headers, quarantined) VALUES xyzzzzzzzzzzzz','0')
```

**Comment by stefaweb** [comment]
Ready to merge.

**Comment by stefaweb** [comment]
I love utf8mb4!

sc

**Comment by stefaweb** [comment]
Next moves are in #507.

**Pull request merged**
